/* broker.c generated by valac 0.56.19, the Vala compiler
 * generated from broker.vala, do not modify */

/* libenchant: Broker
 * Copyright (C) 2003, 2004 Dom Lachowicz
 * Copyright (C) 2016-2026 Reuben Thomas <rrt@sc3d.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along along with this program; if not, see
 * <https://www.gnu.org/licenses/>.
 *
 * In addition, as a special exception, the copyright holders
 * give permission to link the code of this program with
 * non-LGPL Spelling Provider libraries (eg: a MSFT Office
 * spell checker backend) and distribute linked combinations including
 * the two.  You must obey the GNU Lesser General Public License in all
 * respects for all of the code used other than said providers.  If you modify
 * this file, you may extend this exception to your version of the
 * file, but you are not obligated to do so.  If you do not wish to
 * do so, delete this exception statement from your version.
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <gmodule.h>
#include <relocatable.h>
#include <configmake.h>
#include <enchant.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

#define TYPE_ENCHANT_PROVIDER (enchant_provider_get_type ())
#define ENCHANT_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PROVIDER, EnchantProvider))
#define ENCHANT_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PROVIDER, EnchantProviderClass))
#define IS_ENCHANT_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PROVIDER))
#define IS_ENCHANT_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PROVIDER))
#define ENCHANT_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PROVIDER, EnchantProviderClass))

typedef struct _EnchantProvider EnchantProvider;
typedef struct _EnchantProviderClass EnchantProviderClass;
typedef EnchantProvider* (*EnchantProviderInitFunc) (void);
typedef void (*EnchantPreConfigureFunc) (EnchantProvider* provider, const gchar* module_dir);
typedef struct _EnchantBroker EnchantBroker;

#define TYPE_ENCHANT_DICT (enchant_dict_get_type ())
#define ENCHANT_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_DICT, EnchantDict))
#define ENCHANT_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_DICT, EnchantDictClass))
#define IS_ENCHANT_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_DICT))
#define IS_ENCHANT_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_DICT))
#define ENCHANT_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_DICT, EnchantDictClass))

typedef struct _EnchantDict EnchantDict;
typedef struct _EnchantDictClass EnchantDictClass;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_dir_close0(var) ((var == NULL) ? NULL : (var = (g_dir_close (var), NULL)))
#define _enchant_provider_unref0(var) ((var == NULL) ? NULL : (var = (enchant_provider_unref (var), NULL)))
#define _g_module_close0(var) ((var == NULL) ? NULL : (var = (g_module_close (var), NULL)))
typedef struct _EnchantProviderPrivate EnchantProviderPrivate;
typedef void (*ProviderDispose) (EnchantProvider* me);

#define TYPE_ENCHANT_PROVIDER_DICT (enchant_provider_dict_get_type ())
#define ENCHANT_PROVIDER_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDict))
#define ENCHANT_PROVIDER_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDictClass))
#define IS_ENCHANT_PROVIDER_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PROVIDER_DICT))
#define IS_ENCHANT_PROVIDER_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PROVIDER_DICT))
#define ENCHANT_PROVIDER_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDictClass))

typedef struct _EnchantProviderDict EnchantProviderDict;
typedef struct _EnchantProviderDictClass EnchantProviderDictClass;
typedef EnchantProviderDict* (*ProviderRequestDict) (EnchantProvider* me, const gchar* tag);
typedef void (*ProviderDisposeDict) (EnchantProvider* me, EnchantProviderDict* dict);
typedef gint (*ProviderDictionaryExists) (EnchantProvider* me, const gchar* tag);
typedef const gchar* (*ProviderIdentify) (EnchantProvider* me);
typedef const gchar* (*ProviderDescribe) (EnchantProvider* me);
typedef gchar** (*ProviderListDicts) (EnchantProvider* me, size_t* result_length1);
#define _g_io_channel_unref0(var) ((var == NULL) ? NULL : (var = (g_io_channel_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_ENCHANT_PWL_DICT (enchant_pwl_dict_get_type ())
#define ENCHANT_PWL_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PWL_DICT, EnchantPwlDict))
#define ENCHANT_PWL_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PWL_DICT, EnchantPwlDictClass))
#define IS_ENCHANT_PWL_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PWL_DICT))
#define IS_ENCHANT_PWL_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PWL_DICT))
#define ENCHANT_PWL_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PWL_DICT, EnchantPwlDictClass))

typedef struct _EnchantPwlDict EnchantPwlDict;
typedef struct _EnchantPwlDictClass EnchantPwlDictClass;
#define _enchant_provider_dict_unref0(var) ((var == NULL) ? NULL : (var = (enchant_provider_dict_unref (var), NULL)))
#define _enchant_dict_unref0(var) ((var == NULL) ? NULL : (var = (enchant_dict_unref (var), NULL)))

#define TYPE_ENCHANT_COMPOSITE_DICT (enchant_composite_dict_get_type ())
#define ENCHANT_COMPOSITE_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_COMPOSITE_DICT, EnchantCompositeDict))
#define ENCHANT_COMPOSITE_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_COMPOSITE_DICT, EnchantCompositeDictClass))
#define IS_ENCHANT_COMPOSITE_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_COMPOSITE_DICT))
#define IS_ENCHANT_COMPOSITE_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_COMPOSITE_DICT))
#define ENCHANT_COMPOSITE_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_COMPOSITE_DICT, EnchantCompositeDictClass))

typedef struct _EnchantCompositeDict EnchantCompositeDict;
typedef struct _EnchantCompositeDictClass EnchantCompositeDictClass;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _EnchantBroker {
	GSList* provider_list;
	GHashTable* provider_ordering;
	GHashTable* sessions;
	gchar* _error;
};

struct _EnchantProvider {
	GTypeInstance parent_instance;
	volatile int ref_count;
	EnchantProviderPrivate * priv;
	void* user_data;
	GModule* module;
	EnchantBroker* owner;
	ProviderDispose dispose;
	ProviderRequestDict request_dict;
	ProviderDisposeDict dispose_dict;
	ProviderDictionaryExists dictionary_exists;
	ProviderIdentify identify;
	ProviderDescribe describe;
	ProviderListDicts list_dicts;
};

struct _EnchantProviderClass {
	GTypeClass parent_class;
	void (*finalize) (EnchantProvider *self);
};

VALA_EXTERN gchar* normalize_dictionary_tag (const gchar* dict_tag);
VALA_EXTERN gchar* iso_639_from_tag (const gchar* dict_tag);
VALA_EXTERN gpointer enchant_provider_ref (gpointer instance);
VALA_EXTERN void enchant_provider_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_provider (const gchar* name,
                                         const gchar* nick,
                                         const gchar* blurb,
                                         GType object_type,
                                         GParamFlags flags);
VALA_EXTERN void value_set_enchant_provider (GValue* value,
                                 gpointer v_object);
VALA_EXTERN void value_take_enchant_provider (GValue* value,
                                  gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_provider (const GValue* value);
VALA_EXTERN GType enchant_provider_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantProvider, enchant_provider_unref)
VALA_EXTERN void enchant_broker_free (EnchantBroker * self);
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantBroker, enchant_broker_free)
VALA_EXTERN gpointer enchant_dict_ref (gpointer instance);
VALA_EXTERN void enchant_dict_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_dict (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void value_set_enchant_dict (GValue* value,
                             gpointer v_object);
VALA_EXTERN void value_take_enchant_dict (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_dict (const GValue* value);
VALA_EXTERN GType enchant_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantDict, enchant_dict_unref)
static void enchant_broker_instance_init (EnchantBroker * self);
static void _enchant_provider_unref0_ (gpointer var);
static inline void _g_slist_free__enchant_provider_unref0_ (GSList* self);
VALA_EXTERN EnchantBroker* enchant_broker_init (void);
static void enchant_broker_load_providers (EnchantBroker* self);
VALA_EXTERN void enchant_broker_load_provider_ordering (EnchantBroker* self);
static void _enchant_dict_unref0_ (gpointer var);
VALA_EXTERN void enchant_broker_clear_error (EnchantBroker* self);
VALA_EXTERN void enchant_broker_set_error (EnchantBroker* self,
                               const gchar* value);
VALA_EXTERN void enchant_broker_set_ordering (EnchantBroker* self,
                                  const gchar* tag,
                                  const gchar* ordering);
static void enchant_broker_load_providers_in_dir (EnchantBroker* self,
                                           const gchar* dir_name);
VALA_EXTERN gboolean enchant_provider_is_valid (EnchantProvider* provider);
VALA_EXTERN gpointer enchant_provider_dict_ref (gpointer instance);
VALA_EXTERN void enchant_provider_dict_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_provider_dict (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
VALA_EXTERN void value_set_enchant_provider_dict (GValue* value,
                                      gpointer v_object);
VALA_EXTERN void value_take_enchant_provider_dict (GValue* value,
                                       gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_provider_dict (const GValue* value);
VALA_EXTERN GType enchant_provider_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantProviderDict, enchant_provider_dict_unref)
static void enchant_broker_load_ordering_from_file (EnchantBroker* self,
                                             const gchar* file);
static void _g_free0_ (gpointer var);
VALA_EXTERN GSList* enchant_get_conf_dirs (void);
static inline void _g_slist_free__g_free0_ (GSList* self);
VALA_EXTERN GSList* enchant_broker_get_ordered_providers (EnchantBroker* self,
                                              const gchar* tag);
VALA_EXTERN EnchantDict* enchant_broker_request_pwl_dict (EnchantBroker* self,
                                              const gchar* pwl);
VALA_EXTERN EnchantDict* enchant_dict_with_pwl (EnchantProviderDict* dict,
                                    const gchar* pwlname,
                                    const gchar* exclname);
VALA_EXTERN EnchantPwlDict* enchant_pwl_dict_new (void);
VALA_EXTERN EnchantPwlDict* enchant_pwl_dict_construct (GType object_type);
VALA_EXTERN GType enchant_pwl_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantPwlDict, enchant_provider_dict_unref)
VALA_EXTERN EnchantDict* enchant_broker_new_dict (EnchantBroker* self,
                                      EnchantDict* session);
static EnchantDict* _enchant_broker_request_dict (EnchantBroker* self,
                                           const gchar* tag,
                                           const gchar* pwl);
VALA_EXTERN EnchantDict* enchant_dict_with_implicit_pwl (EnchantProviderDict* dict,
                                             const gchar* lang,
                                             const gchar* pwl);
VALA_EXTERN EnchantDict* enchant_broker_request_dict_with_pwl (EnchantBroker* self,
                                                   const gchar* composite_tag,
                                                   const gchar* pwl);
VALA_EXTERN GType enchant_composite_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantCompositeDict, enchant_provider_dict_unref)
VALA_EXTERN EnchantCompositeDict* enchant_composite_dict_new (EnchantBroker* broker,
                                                  GSList* session_list,
                                                  const gchar* tag);
VALA_EXTERN EnchantCompositeDict* enchant_composite_dict_construct (GType object_type,
                                                        EnchantBroker* broker,
                                                        GSList* session_list,
                                                        const gchar* tag);
VALA_EXTERN EnchantDict* enchant_broker_request_dict (EnchantBroker* self,
                                          const gchar* tag);
VALA_EXTERN void enchant_broker_describe (EnchantBroker* self,
                              EnchantBrokerDescribeFn fn,
                              void* user_data);
VALA_EXTERN void enchant_broker_list_dicts (EnchantBroker* self,
                                EnchantDictDescribeFn fn,
                                void* user_data);
static gint _enchant_broker_dict_exists (EnchantBroker* self,
                                  const gchar* tag);
VALA_EXTERN gint _enchant_provider_dictionary_exists (EnchantProvider* self,
                                          const gchar* tag);
VALA_EXTERN gint enchant_broker_dict_exists (EnchantBroker* self,
                                 const gchar* tag);
VALA_EXTERN void enchant_broker_free_dict (EnchantBroker* self,
                               EnchantDict* session);
VALA_EXTERN const gchar* enchant_broker_get_error (EnchantBroker* self);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
#line 1415 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1416 "glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1416 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1417 "glib-2.0.vapi"
	g_strstrip (_result_);
#line 1418 "glib-2.0.vapi"
	result = _result_;
#line 1418 "glib-2.0.vapi"
	return result;
#line 306 "broker.c"
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1503 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1503 "glib-2.0.vapi"
	end = _tmp0_;
#line 1504 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1504 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1505 "glib-2.0.vapi"
		result = maxlen;
#line 1505 "glib-2.0.vapi"
		return result;
#line 329 "broker.c"
	} else {
		gchar* _tmp2_;
#line 1507 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1507 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1507 "glib-2.0.vapi"
		return result;
#line 338 "broker.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1514 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1516 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1516 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 357 "broker.c"
	} else {
#line 1516 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 361 "broker.c"
	}
#line 1516 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1518 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 367 "broker.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1520 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1520 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1520 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 377 "broker.c"
	}
#line 1523 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1524 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1525 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 385 "broker.c"
	} else {
#line 1527 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 389 "broker.c"
	}
#line 1529 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1530 "glib-2.0.vapi"
		len = string_length - offset;
#line 395 "broker.c"
	}
#line 1532 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1533 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1533 "glib-2.0.vapi"
	result = _tmp3_;
#line 1533 "glib-2.0.vapi"
	return result;
#line 405 "broker.c"
}

static gint
string_index_of_char (const gchar* self,
                      gunichar c,
                      gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result;
#line 1204 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, -1);
#line 1205 "glib-2.0.vapi"
	_tmp0_ = g_utf8_strchr (((gchar*) self) + start_index, (gssize) -1, c);
#line 1205 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1207 "glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1207 "glib-2.0.vapi"
	if (_tmp1_ != NULL) {
#line 427 "broker.c"
		gchar* _tmp2_;
#line 1208 "glib-2.0.vapi"
		_tmp2_ = _result_;
#line 1208 "glib-2.0.vapi"
		result = (gint) (_tmp2_ - ((gchar*) self));
#line 1208 "glib-2.0.vapi"
		return result;
#line 435 "broker.c"
	} else {
#line 1210 "glib-2.0.vapi"
		result = -1;
#line 1210 "glib-2.0.vapi"
		return result;
#line 441 "broker.c"
	}
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1283 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1284 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1284 "glib-2.0.vapi"
	result = _tmp0_;
#line 1284 "glib-2.0.vapi"
	return result;
#line 459 "broker.c"
}

gchar*
normalize_dictionary_tag (const gchar* dict_tag)
{
	gchar* new_tag = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	GString* sb = NULL;
	GString* _tmp7_;
	gint i = 0;
	gboolean _tmp17_ = FALSE;
	const gchar* _tmp18_;
	const gchar* _tmp21_;
	GString* _tmp32_;
	const gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* result;
#line 33 "broker.vala"
	g_return_val_if_fail (dict_tag != NULL, NULL);
#line 34 "broker.vala"
	_tmp0_ = string_strip (dict_tag);
#line 34 "broker.vala"
	new_tag = _tmp0_;
#line 37 "broker.vala"
	_tmp1_ = new_tag;
#line 37 "broker.vala"
	_tmp2_ = new_tag;
#line 37 "broker.vala"
	_tmp3_ = string_substring (_tmp1_, (glong) 0, (glong) string_index_of_char (_tmp2_, (gunichar) '@', 0));
#line 37 "broker.vala"
	_g_free0 (new_tag);
#line 37 "broker.vala"
	new_tag = _tmp3_;
#line 39 "broker.vala"
	_tmp4_ = new_tag;
#line 39 "broker.vala"
	_tmp5_ = new_tag;
#line 39 "broker.vala"
	_tmp6_ = string_substring (_tmp4_, (glong) 0, (glong) string_index_of_char (_tmp5_, (gunichar) '.', 0));
#line 39 "broker.vala"
	_g_free0 (new_tag);
#line 39 "broker.vala"
	new_tag = _tmp6_;
#line 42 "broker.vala"
	_tmp7_ = g_string_new ("");
#line 42 "broker.vala"
	sb = _tmp7_;
#line 513 "broker.c"
	{
		gboolean _tmp8_ = FALSE;
#line 44 "broker.vala"
		i = 0;
#line 44 "broker.vala"
		_tmp8_ = TRUE;
#line 44 "broker.vala"
		while (TRUE) {
#line 522 "broker.c"
			gboolean _tmp10_ = FALSE;
			gboolean _tmp11_ = FALSE;
			const gchar* _tmp12_;
			GString* _tmp15_;
			const gchar* _tmp16_;
#line 44 "broker.vala"
			if (!_tmp8_) {
#line 530 "broker.c"
				gint _tmp9_;
#line 46 "broker.vala"
				i = i + 1;
#line 46 "broker.vala"
				_tmp9_ = i;
#line 536 "broker.c"
			}
#line 44 "broker.vala"
			_tmp8_ = FALSE;
#line 45 "broker.vala"
			_tmp12_ = new_tag;
#line 45 "broker.vala"
			if (string_get (_tmp12_, (glong) i) != '\0') {
#line 544 "broker.c"
				const gchar* _tmp13_;
#line 45 "broker.vala"
				_tmp13_ = new_tag;
#line 45 "broker.vala"
				_tmp11_ = string_get (_tmp13_, (glong) i) != '-';
#line 550 "broker.c"
			} else {
#line 45 "broker.vala"
				_tmp11_ = FALSE;
#line 554 "broker.c"
			}
#line 45 "broker.vala"
			if (_tmp11_) {
#line 558 "broker.c"
				const gchar* _tmp14_;
#line 45 "broker.vala"
				_tmp14_ = new_tag;
#line 45 "broker.vala"
				_tmp10_ = string_get (_tmp14_, (glong) i) != '_';
#line 564 "broker.c"
			} else {
#line 45 "broker.vala"
				_tmp10_ = FALSE;
#line 568 "broker.c"
			}
#line 45 "broker.vala"
			if (!_tmp10_) {
#line 45 "broker.vala"
				break;
#line 574 "broker.c"
			}
#line 47 "broker.vala"
			_tmp15_ = sb;
#line 47 "broker.vala"
			_tmp16_ = new_tag;
#line 47 "broker.vala"
			g_string_append_c (_tmp15_, g_ascii_tolower (string_get (_tmp16_, (glong) i)));
#line 582 "broker.c"
		}
	}
#line 50 "broker.vala"
	_tmp18_ = new_tag;
#line 50 "broker.vala"
	if (string_get (_tmp18_, (glong) i) == '-') {
#line 50 "broker.vala"
		_tmp17_ = TRUE;
#line 591 "broker.c"
	} else {
		const gchar* _tmp19_;
#line 50 "broker.vala"
		_tmp19_ = new_tag;
#line 50 "broker.vala"
		_tmp17_ = string_get (_tmp19_, (glong) i) == '_';
#line 598 "broker.c"
	}
#line 50 "broker.vala"
	if (_tmp17_) {
#line 602 "broker.c"
		GString* _tmp20_;
#line 51 "broker.vala"
		_tmp20_ = sb;
#line 51 "broker.vala"
		g_string_append_c (_tmp20_, '_');
#line 608 "broker.c"
	}
#line 55 "broker.vala"
	_tmp21_ = new_tag;
#line 55 "broker.vala"
	if (string_get (_tmp21_, (glong) i) != '\0') {
#line 614 "broker.c"
		{
			gint _tmp22_;
			gboolean _tmp23_ = FALSE;
#line 56 "broker.vala"
			i = i + 1;
#line 56 "broker.vala"
			_tmp22_ = i;
#line 56 "broker.vala"
			_tmp23_ = TRUE;
#line 56 "broker.vala"
			while (TRUE) {
#line 626 "broker.c"
				const gchar* _tmp25_;
				GString* _tmp26_;
				const gchar* _tmp27_;
#line 56 "broker.vala"
				if (!_tmp23_) {
#line 632 "broker.c"
					gint _tmp24_;
#line 56 "broker.vala"
					i = i + 1;
#line 56 "broker.vala"
					_tmp24_ = i;
#line 638 "broker.c"
				}
#line 56 "broker.vala"
				_tmp23_ = FALSE;
#line 56 "broker.vala"
				_tmp25_ = new_tag;
#line 56 "broker.vala"
				if (!g_ascii_isalnum (string_get (_tmp25_, (glong) i))) {
#line 56 "broker.vala"
					break;
#line 648 "broker.c"
				}
#line 57 "broker.vala"
				_tmp26_ = sb;
#line 57 "broker.vala"
				_tmp27_ = new_tag;
#line 57 "broker.vala"
				g_string_append_c (_tmp26_, g_ascii_toupper (string_get (_tmp27_, (glong) i)));
#line 656 "broker.c"
			}
		}
	}
#line 60 "broker.vala"
	while (TRUE) {
#line 662 "broker.c"
		const gchar* _tmp28_;
		GString* _tmp29_;
		const gchar* _tmp30_;
		gint _tmp31_;
#line 60 "broker.vala"
		_tmp28_ = new_tag;
#line 60 "broker.vala"
		if (!(string_get (_tmp28_, (glong) i) != '\0')) {
#line 60 "broker.vala"
			break;
#line 673 "broker.c"
		}
#line 61 "broker.vala"
		_tmp29_ = sb;
#line 61 "broker.vala"
		_tmp30_ = new_tag;
#line 61 "broker.vala"
		_tmp31_ = i;
#line 61 "broker.vala"
		i = _tmp31_ + 1;
#line 61 "broker.vala"
		g_string_append_c (_tmp29_, string_get (_tmp30_, (glong) _tmp31_));
#line 685 "broker.c"
	}
#line 63 "broker.vala"
	_tmp32_ = sb;
#line 63 "broker.vala"
	_tmp33_ = _tmp32_->str;
#line 63 "broker.vala"
	_tmp34_ = g_strdup (_tmp33_);
#line 63 "broker.vala"
	result = _tmp34_;
#line 63 "broker.vala"
	_g_string_free0 (sb);
#line 63 "broker.vala"
	_g_free0 (new_tag);
#line 63 "broker.vala"
	return result;
#line 701 "broker.c"
}

gchar*
iso_639_from_tag (const gchar* dict_tag)
{
	gchar* _tmp0_;
	gchar* result;
#line 66 "broker.vala"
	g_return_val_if_fail (dict_tag != NULL, NULL);
#line 67 "broker.vala"
	_tmp0_ = string_substring (dict_tag, (glong) 0, (glong) string_index_of_char (dict_tag, (gunichar) '_', 0));
#line 67 "broker.vala"
	result = _tmp0_;
#line 67 "broker.vala"
	return result;
#line 717 "broker.c"
}

static void
_enchant_provider_unref0_ (gpointer var)
{
#line 77 "broker.vala"
	(var == NULL) ? NULL : (var = (enchant_provider_unref (var), NULL));
#line 725 "broker.c"
}

static inline void
_g_slist_free__enchant_provider_unref0_ (GSList* self)
{
#line 77 "broker.vala"
	g_slist_free_full (self, (GDestroyNotify) _enchant_provider_unref0_);
#line 733 "broker.c"
}

static void
_enchant_dict_unref0_ (gpointer var)
{
#line 90 "broker.vala"
	(var == NULL) ? NULL : (var = (enchant_dict_unref (var), NULL));
#line 741 "broker.c"
}

EnchantBroker*
enchant_broker_init (void)
{
	EnchantBroker* self;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
#line 84 "broker.vala"
	self = g_slice_new0 (EnchantBroker);
#line 84 "broker.vala"
	enchant_broker_instance_init (self);
#line 85 "broker.vala"
	if (!g_module_supported ()) {
#line 86 "broker.vala"
		return self;
#line 759 "broker.c"
	}
#line 88 "broker.vala"
	enchant_broker_load_providers (self);
#line 89 "broker.vala"
	enchant_broker_load_provider_ordering (self);
#line 90 "broker.vala"
	_tmp0_ = g_direct_hash;
#line 90 "broker.vala"
	_tmp1_ = g_direct_equal;
#line 90 "broker.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, NULL, _enchant_dict_unref0_);
#line 90 "broker.vala"
	_g_hash_table_unref0 (self->sessions);
#line 90 "broker.vala"
	self->sessions = _tmp2_;
#line 84 "broker.vala"
	return self;
#line 777 "broker.c"
}

void
enchant_broker_clear_error (EnchantBroker* self)
{
#line 99 "broker.vala"
	g_return_if_fail (self != NULL);
#line 100 "broker.vala"
	enchant_broker_set_error (self, NULL);
#line 787 "broker.c"
}

void
enchant_broker_set_ordering (EnchantBroker* self,
                             const gchar* tag,
                             const gchar* ordering)
{
	gboolean _tmp0_ = FALSE;
	gchar* tag_dupl = NULL;
	gchar* _tmp1_;
	gchar* ordering_dupl = NULL;
	gchar* _tmp2_;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	const gchar* _tmp6_;
#line 108 "broker.vala"
	g_return_if_fail (self != NULL);
#line 109 "broker.vala"
	enchant_broker_clear_error (self);
#line 111 "broker.vala"
	if (tag == NULL) {
#line 111 "broker.vala"
		_tmp0_ = TRUE;
#line 812 "broker.c"
	} else {
#line 111 "broker.vala"
		_tmp0_ = ordering == NULL;
#line 816 "broker.c"
	}
#line 111 "broker.vala"
	if (_tmp0_) {
#line 112 "broker.vala"
		return;
#line 822 "broker.c"
	}
#line 114 "broker.vala"
	_tmp1_ = normalize_dictionary_tag (tag);
#line 114 "broker.vala"
	tag_dupl = _tmp1_;
#line 115 "broker.vala"
	_tmp2_ = string_strip (ordering);
#line 115 "broker.vala"
	ordering_dupl = _tmp2_;
#line 117 "broker.vala"
	_tmp6_ = tag_dupl;
#line 117 "broker.vala"
	if (_tmp6_ != NULL) {
#line 836 "broker.c"
		const gchar* _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
#line 117 "broker.vala"
		_tmp7_ = tag_dupl;
#line 117 "broker.vala"
		_tmp8_ = strlen (_tmp7_);
#line 117 "broker.vala"
		_tmp9_ = _tmp8_;
#line 117 "broker.vala"
		_tmp5_ = _tmp9_ > 0;
#line 848 "broker.c"
	} else {
#line 117 "broker.vala"
		_tmp5_ = FALSE;
#line 852 "broker.c"
	}
#line 117 "broker.vala"
	if (_tmp5_) {
#line 856 "broker.c"
		const gchar* _tmp10_;
#line 118 "broker.vala"
		_tmp10_ = ordering_dupl;
#line 118 "broker.vala"
		_tmp4_ = _tmp10_ != NULL;
#line 862 "broker.c"
	} else {
#line 117 "broker.vala"
		_tmp4_ = FALSE;
#line 866 "broker.c"
	}
#line 117 "broker.vala"
	if (_tmp4_) {
#line 870 "broker.c"
		const gchar* _tmp11_;
		gint _tmp12_;
		gint _tmp13_;
#line 118 "broker.vala"
		_tmp11_ = ordering_dupl;
#line 118 "broker.vala"
		_tmp12_ = strlen (_tmp11_);
#line 118 "broker.vala"
		_tmp13_ = _tmp12_;
#line 118 "broker.vala"
		_tmp3_ = _tmp13_ > 0;
#line 882 "broker.c"
	} else {
#line 117 "broker.vala"
		_tmp3_ = FALSE;
#line 886 "broker.c"
	}
#line 117 "broker.vala"
	if (_tmp3_) {
#line 890 "broker.c"
		GHashTable* _tmp14_;
		const gchar* _tmp15_;
		gchar* _tmp16_;
		const gchar* _tmp17_;
		gchar* _tmp18_;
#line 119 "broker.vala"
		_tmp14_ = self->provider_ordering;
#line 119 "broker.vala"
		_tmp15_ = tag_dupl;
#line 119 "broker.vala"
		_tmp16_ = g_strdup (_tmp15_);
#line 119 "broker.vala"
		_tmp17_ = ordering_dupl;
#line 119 "broker.vala"
		_tmp18_ = g_strdup (_tmp17_);
#line 119 "broker.vala"
		g_hash_table_insert (_tmp14_, _tmp16_, _tmp18_);
#line 908 "broker.c"
	}
#line 108 "broker.vala"
	_g_free0 (ordering_dupl);
#line 108 "broker.vala"
	_g_free0 (tag_dupl);
#line 914 "broker.c"
}

static gchar*
_vala_gnulib_relocate (const gchar* path)
{
	gchar* newpath = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* result;
#line 77 "gnu.vapi"
	g_return_val_if_fail (path != NULL, NULL);
#line 78 "gnu.vapi"
	_tmp0_ = (gchar*) relocate (path);
#line 78 "gnu.vapi"
	newpath = _tmp0_;
#line 79 "gnu.vapi"
	_tmp1_ = newpath;
#line 79 "gnu.vapi"
	if (_tmp1_ != path) {
#line 934 "broker.c"
		gchar* _tmp2_;
#line 82 "gnu.vapi"
		_tmp2_ = newpath;
#line 82 "gnu.vapi"
		newpath = NULL;
#line 82 "gnu.vapi"
		result = (gchar*) _tmp2_;
#line 82 "gnu.vapi"
		return result;
#line 944 "broker.c"
	} else {
		gchar* _tmp3_;
		gchar* _tmp4_;
#line 85 "gnu.vapi"
		_tmp3_ = newpath;
#line 85 "gnu.vapi"
		_tmp4_ = g_strdup ((const gchar*) _tmp3_);
#line 85 "gnu.vapi"
		result = _tmp4_;
#line 85 "gnu.vapi"
		return result;
#line 956 "broker.c"
	}
}

static void
enchant_broker_load_providers (EnchantBroker* self)
{
	gchar* module_dir = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
#line 122 "broker.vala"
	g_return_if_fail (self != NULL);
#line 123 "broker.vala"
	_tmp0_ = g_strdup_printf ("%s-%s", PKGLIBDIR, ENCHANT_MAJOR_VERSION);
#line 123 "broker.vala"
	_tmp1_ = _tmp0_;
#line 123 "broker.vala"
	_tmp2_ = _vala_gnulib_relocate (_tmp1_);
#line 123 "broker.vala"
	_tmp3_ = _tmp2_;
#line 123 "broker.vala"
	_g_free0 (_tmp1_);
#line 123 "broker.vala"
	module_dir = _tmp3_;
#line 124 "broker.vala"
	_tmp4_ = module_dir;
#line 124 "broker.vala"
	if (_tmp4_ != NULL) {
#line 987 "broker.c"
		const gchar* _tmp5_;
#line 125 "broker.vala"
		_tmp5_ = module_dir;
#line 125 "broker.vala"
		enchant_broker_load_providers_in_dir (self, _tmp5_);
#line 993 "broker.c"
	}
#line 122 "broker.vala"
	_g_free0 (module_dir);
#line 997 "broker.c"
}

static void
enchant_broker_load_providers_in_dir (EnchantBroker* self,
                                      const gchar* dir_name)
{
	GDir* dir = NULL;
	gchar* dir_entry = NULL;
	GError* _inner_error0_ = NULL;
#line 128 "broker.vala"
	g_return_if_fail (self != NULL);
#line 128 "broker.vala"
	g_return_if_fail (dir_name != NULL);
#line 1011 "broker.c"
	{
		GDir* _tmp0_ = NULL;
		GDir* _tmp1_;
		GDir* _tmp2_;
#line 131 "broker.vala"
		_tmp1_ = g_dir_open (dir_name, (guint) 0, &_inner_error0_);
#line 131 "broker.vala"
		_tmp0_ = _tmp1_;
#line 131 "broker.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 131 "broker.vala"
			if (_inner_error0_->domain == G_FILE_ERROR) {
#line 1024 "broker.c"
				goto __catch0_g_file_error;
			}
#line 131 "broker.vala"
			_g_dir_close0 (dir);
#line 131 "broker.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 131 "broker.vala"
			g_clear_error (&_inner_error0_);
#line 131 "broker.vala"
			return;
#line 1035 "broker.c"
		}
#line 131 "broker.vala"
		_tmp2_ = _tmp0_;
#line 131 "broker.vala"
		_tmp0_ = NULL;
#line 131 "broker.vala"
		_g_dir_close0 (dir);
#line 131 "broker.vala"
		dir = _tmp2_;
#line 130 "broker.vala"
		_g_dir_close0 (_tmp0_);
#line 1047 "broker.c"
	}
	goto __finally0;
	__catch0_g_file_error:
	{
#line 130 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 133 "broker.vala"
		_g_dir_close0 (dir);
#line 133 "broker.vala"
		return;
#line 1058 "broker.c"
	}
	__finally0:
#line 130 "broker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 130 "broker.vala"
		_g_dir_close0 (dir);
#line 130 "broker.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 130 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 130 "broker.vala"
		return;
#line 1071 "broker.c"
	}
#line 137 "broker.vala"
	while (TRUE) {
#line 1075 "broker.c"
		GDir* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		const gchar* _tmp6_;
		GModule* module = NULL;
		EnchantProvider* provider = NULL;
		const gchar* _tmp7_;
		EnchantProvider* _tmp30_;
#line 137 "broker.vala"
		_tmp3_ = dir;
#line 137 "broker.vala"
		_tmp4_ = g_dir_read_name (_tmp3_);
#line 137 "broker.vala"
		_tmp5_ = g_strdup (_tmp4_);
#line 137 "broker.vala"
		_g_free0 (dir_entry);
#line 137 "broker.vala"
		dir_entry = _tmp5_;
#line 137 "broker.vala"
		_tmp6_ = dir_entry;
#line 137 "broker.vala"
		if (!(_tmp6_ != NULL)) {
#line 137 "broker.vala"
			break;
#line 1100 "broker.c"
		}
#line 138 "broker.vala"
		module = NULL;
#line 139 "broker.vala"
		provider = NULL;
#line 141 "broker.vala"
		_tmp7_ = dir_entry;
#line 141 "broker.vala"
		if (string_get (_tmp7_, (glong) 0) != '.') {
#line 1110 "broker.c"
			gchar* filename = NULL;
			const gchar* _tmp8_;
			gchar* _tmp9_;
#line 142 "broker.vala"
			_tmp8_ = dir_entry;
#line 142 "broker.vala"
			_tmp9_ = g_build_filename (dir_name, _tmp8_, NULL);
#line 142 "broker.vala"
			filename = _tmp9_;
#line 1120 "broker.c"
			{
				GModule* _tmp10_ = NULL;
				const gchar* _tmp11_;
				GModule* _tmp12_;
				GModule* _tmp13_;
				void* init_func = NULL;
				gboolean _tmp14_ = FALSE;
				GModule* _tmp15_;
				void* _tmp16_ = NULL;
				gboolean _tmp17_;
#line 144 "broker.vala"
				_tmp11_ = filename;
#line 144 "broker.vala"
				_tmp12_ = g_module_open_full (_tmp11_, 0, &_inner_error0_);
#line 144 "broker.vala"
				_tmp10_ = _tmp12_;
#line 144 "broker.vala"
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 144 "broker.vala"
					if (_inner_error0_->domain == G_MODULE_ERROR) {
#line 1141 "broker.c"
						goto __catch1_g_module_error;
					}
#line 144 "broker.vala"
					_g_free0 (filename);
#line 144 "broker.vala"
					_enchant_provider_unref0 (provider);
#line 144 "broker.vala"
					_g_module_close0 (module);
#line 144 "broker.vala"
					_g_free0 (dir_entry);
#line 144 "broker.vala"
					_g_dir_close0 (dir);
#line 144 "broker.vala"
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 144 "broker.vala"
					g_clear_error (&_inner_error0_);
#line 144 "broker.vala"
					return;
#line 1160 "broker.c"
				}
#line 144 "broker.vala"
				_tmp13_ = _tmp10_;
#line 144 "broker.vala"
				_tmp10_ = NULL;
#line 144 "broker.vala"
				_g_module_close0 (module);
#line 144 "broker.vala"
				module = _tmp13_;
#line 146 "broker.vala"
				_tmp15_ = module;
#line 146 "broker.vala"
				_tmp17_ = g_module_symbol (_tmp15_, "init_enchant_provider", &_tmp16_);
#line 146 "broker.vala"
				init_func = _tmp16_;
#line 146 "broker.vala"
				if (_tmp17_) {
#line 1178 "broker.c"
					void* _tmp18_;
#line 147 "broker.vala"
					_tmp18_ = init_func;
#line 147 "broker.vala"
					_tmp14_ = _tmp18_ != NULL;
#line 1184 "broker.c"
				} else {
#line 146 "broker.vala"
					_tmp14_ = FALSE;
#line 1188 "broker.c"
				}
#line 146 "broker.vala"
				if (_tmp14_) {
#line 1192 "broker.c"
					void* _tmp19_;
					EnchantProvider* _tmp20_;
					EnchantProvider* _tmp21_;
#line 148 "broker.vala"
					_tmp19_ = init_func;
#line 148 "broker.vala"
					_tmp20_ = ((EnchantProviderInitFunc) _tmp19_) ();
#line 148 "broker.vala"
					_enchant_provider_unref0 (provider);
#line 148 "broker.vala"
					provider = _tmp20_;
#line 149 "broker.vala"
					_tmp21_ = provider;
#line 149 "broker.vala"
					if (!enchant_provider_is_valid (_tmp21_)) {
#line 1208 "broker.c"
						const gchar* _tmp22_;
						EnchantProvider* _tmp23_;
#line 150 "broker.vala"
						_tmp22_ = dir_entry;
#line 150 "broker.vala"
						g_warning ("broker.vala:150: Error loading plugin: %s's init_enchant_provider retu" \
"rned invalid provider", _tmp22_);
#line 151 "broker.vala"
						_tmp23_ = provider;
#line 151 "broker.vala"
						if (_tmp23_ != NULL) {
#line 1219 "broker.c"
							EnchantProvider* _tmp24_;
							ProviderDispose _tmp25_;
#line 152 "broker.vala"
							_tmp24_ = provider;
#line 152 "broker.vala"
							_tmp25_ = _tmp24_->dispose;
#line 152 "broker.vala"
							if (_tmp25_ != NULL) {
#line 1228 "broker.c"
								EnchantProvider* _tmp26_;
								ProviderDispose _tmp27_;
								EnchantProvider* _tmp28_;
#line 153 "broker.vala"
								_tmp26_ = provider;
#line 153 "broker.vala"
								_tmp27_ = _tmp26_->dispose;
#line 153 "broker.vala"
								_tmp28_ = provider;
#line 153 "broker.vala"
								_tmp27_ (_tmp28_);
#line 1240 "broker.c"
							}
#line 154 "broker.vala"
							_enchant_provider_unref0 (provider);
#line 154 "broker.vala"
							provider = NULL;
#line 1246 "broker.c"
						}
					}
				}
#line 143 "broker.vala"
				_g_module_close0 (_tmp10_);
#line 1252 "broker.c"
			}
			goto __finally1;
			__catch1_g_module_error:
			{
				const gchar* _tmp29_;
#line 143 "broker.vala"
				g_clear_error (&_inner_error0_);
#line 159 "broker.vala"
				_tmp29_ = g_module_error ();
#line 159 "broker.vala"
				g_warning ("broker.vala:159: Error loading plugin: %s", _tmp29_);
#line 1264 "broker.c"
			}
			__finally1:
#line 143 "broker.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 143 "broker.vala"
				_g_free0 (filename);
#line 143 "broker.vala"
				_enchant_provider_unref0 (provider);
#line 143 "broker.vala"
				_g_module_close0 (module);
#line 143 "broker.vala"
				_g_free0 (dir_entry);
#line 143 "broker.vala"
				_g_dir_close0 (dir);
#line 143 "broker.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 143 "broker.vala"
				g_clear_error (&_inner_error0_);
#line 143 "broker.vala"
				return;
#line 1285 "broker.c"
			}
#line 141 "broker.vala"
			_g_free0 (filename);
#line 1289 "broker.c"
		}
#line 162 "broker.vala"
		_tmp30_ = provider;
#line 162 "broker.vala"
		if (_tmp30_ != NULL) {
#line 1295 "broker.c"
			EnchantProvider* _tmp31_;
			GModule* _tmp32_;
			EnchantProvider* _tmp33_;
			EnchantProvider* _tmp34_;
#line 163 "broker.vala"
			_tmp31_ = provider;
#line 163 "broker.vala"
			_tmp32_ = module;
#line 163 "broker.vala"
			module = NULL;
#line 163 "broker.vala"
			_g_module_close0 (_tmp31_->module);
#line 163 "broker.vala"
			_tmp31_->module = _tmp32_;
#line 164 "broker.vala"
			_tmp33_ = provider;
#line 164 "broker.vala"
			_tmp33_->owner = self;
#line 165 "broker.vala"
			_tmp34_ = provider;
#line 165 "broker.vala"
			provider = NULL;
#line 165 "broker.vala"
			self->provider_list = g_slist_append (self->provider_list, _tmp34_);
#line 1320 "broker.c"
		}
#line 137 "broker.vala"
		_enchant_provider_unref0 (provider);
#line 137 "broker.vala"
		_g_module_close0 (module);
#line 1326 "broker.c"
	}
#line 128 "broker.vala"
	_g_free0 (dir_entry);
#line 128 "broker.vala"
	_g_dir_close0 (dir);
#line 1332 "broker.c"
}

static void
enchant_broker_load_ordering_from_file (EnchantBroker* self,
                                        const gchar* file)
{
	GIOChannel* ch = NULL;
	GIOChannel* _tmp5_;
	gchar* line = NULL;
	gsize terminator = 0UL;
	GError* _inner_error0_ = NULL;
#line 170 "broker.vala"
	g_return_if_fail (self != NULL);
#line 170 "broker.vala"
	g_return_if_fail (file != NULL);
#line 171 "broker.vala"
	ch = NULL;
#line 1350 "broker.c"
	{
		GIOChannel* _tmp0_ = NULL;
		GIOChannel* _tmp1_;
		GIOChannel* _tmp2_;
#line 173 "broker.vala"
		_tmp1_ = g_io_channel_new_file (file, "r", &_inner_error0_);
#line 173 "broker.vala"
		_tmp0_ = _tmp1_;
#line 173 "broker.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 173 "broker.vala"
			if (_inner_error0_->domain == G_FILE_ERROR) {
#line 1363 "broker.c"
				goto __catch0_g_file_error;
			}
#line 173 "broker.vala"
			_g_io_channel_unref0 (ch);
#line 173 "broker.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 173 "broker.vala"
			g_clear_error (&_inner_error0_);
#line 173 "broker.vala"
			return;
#line 1374 "broker.c"
		}
#line 173 "broker.vala"
		_tmp2_ = _tmp0_;
#line 173 "broker.vala"
		_tmp0_ = NULL;
#line 173 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 173 "broker.vala"
		ch = _tmp2_;
#line 172 "broker.vala"
		_g_io_channel_unref0 (_tmp0_);
#line 1386 "broker.c"
	}
	goto __finally0;
	__catch0_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp3_;
		const gchar* _tmp4_;
#line 172 "broker.vala"
		e = _inner_error0_;
#line 172 "broker.vala"
		_inner_error0_ = NULL;
#line 175 "broker.vala"
		_tmp3_ = e;
#line 175 "broker.vala"
		_tmp4_ = _tmp3_->message;
#line 175 "broker.vala"
		g_debug ("broker.vala:175: could not open ordering file %s: %s", file, _tmp4_);
#line 176 "broker.vala"
		_g_error_free0 (e);
#line 176 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 176 "broker.vala"
		return;
#line 1410 "broker.c"
	}
	__finally0:
#line 172 "broker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 172 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 172 "broker.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 172 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 172 "broker.vala"
		return;
#line 1423 "broker.c"
	}
#line 178 "broker.vala"
	_tmp5_ = ch;
#line 178 "broker.vala"
	_vala_assert (_tmp5_ != NULL, "ch != null");
#line 180 "broker.vala"
	g_debug ("broker.vala:180: reading ordering file %s", file);
#line 1431 "broker.c"
	{
#line 184 "broker.vala"
		while (TRUE) {
#line 1435 "broker.c"
			GIOStatus _tmp6_ = 0;
			GIOChannel* _tmp7_;
			gchar* _tmp8_ = NULL;
			gsize _tmp9_ = 0UL;
			GIOStatus _tmp10_;
			gint colon = 0;
			const gchar* _tmp11_;
#line 184 "broker.vala"
			_tmp7_ = ch;
#line 184 "broker.vala"
			_tmp10_ = g_io_channel_read_line (_tmp7_, &_tmp8_, NULL, &_tmp9_, &_inner_error0_);
#line 184 "broker.vala"
			_g_free0 (line);
#line 184 "broker.vala"
			line = _tmp8_;
#line 184 "broker.vala"
			terminator = _tmp9_;
#line 184 "broker.vala"
			_tmp6_ = _tmp10_;
#line 184 "broker.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 184 "broker.vala"
				if (_inner_error0_->domain == G_CONVERT_ERROR) {
#line 1459 "broker.c"
					goto __catch1_g_convert_error;
				}
#line 184 "broker.vala"
				if (_inner_error0_->domain == G_IO_CHANNEL_ERROR) {
#line 1464 "broker.c"
					goto __catch1_g_io_channel_error;
				}
#line 184 "broker.vala"
				_g_free0 (line);
#line 184 "broker.vala"
				_g_io_channel_unref0 (ch);
#line 184 "broker.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 184 "broker.vala"
				g_clear_error (&_inner_error0_);
#line 184 "broker.vala"
				return;
#line 1477 "broker.c"
			}
#line 184 "broker.vala"
			if (!(G_IO_STATUS_NORMAL == _tmp6_)) {
#line 184 "broker.vala"
				break;
#line 1483 "broker.c"
			}
#line 185 "broker.vala"
			_tmp11_ = line;
#line 185 "broker.vala"
			colon = string_index_of_char (_tmp11_, (gunichar) ':', 0);
#line 186 "broker.vala"
			if (colon != -1) {
#line 1491 "broker.c"
				gchar* tag = NULL;
				const gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* ordering = NULL;
				const gchar* _tmp14_;
				gchar* _tmp15_;
				const gchar* _tmp16_;
				const gchar* _tmp17_;
#line 187 "broker.vala"
				_tmp12_ = line;
#line 187 "broker.vala"
				_tmp13_ = string_substring (_tmp12_, (glong) 0, (glong) colon);
#line 187 "broker.vala"
				tag = _tmp13_;
#line 188 "broker.vala"
				_tmp14_ = line;
#line 188 "broker.vala"
				_tmp15_ = string_substring (_tmp14_, (glong) (colon + 1), (((glong) terminator) - colon) - 1);
#line 188 "broker.vala"
				ordering = _tmp15_;
#line 189 "broker.vala"
				_tmp16_ = tag;
#line 189 "broker.vala"
				_tmp17_ = ordering;
#line 189 "broker.vala"
				enchant_broker_set_ordering (self, _tmp16_, _tmp17_);
#line 186 "broker.vala"
				_g_free0 (ordering);
#line 186 "broker.vala"
				_g_free0 (tag);
#line 1522 "broker.c"
			}
		}
	}
	goto __finally1;
	__catch1_g_convert_error:
	{
#line 183 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 193 "broker.vala"
		_g_free0 (line);
#line 193 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 193 "broker.vala"
		return;
#line 1537 "broker.c"
	}
	goto __finally1;
	__catch1_g_io_channel_error:
	{
#line 183 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 195 "broker.vala"
		_g_free0 (line);
#line 195 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 195 "broker.vala"
		return;
#line 1550 "broker.c"
	}
	__finally1:
#line 183 "broker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 183 "broker.vala"
		_g_free0 (line);
#line 183 "broker.vala"
		_g_io_channel_unref0 (ch);
#line 183 "broker.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 183 "broker.vala"
		g_clear_error (&_inner_error0_);
#line 183 "broker.vala"
		return;
#line 1565 "broker.c"
	}
#line 170 "broker.vala"
	_g_free0 (line);
#line 170 "broker.vala"
	_g_io_channel_unref0 (ch);
#line 1571 "broker.c"
}

static void
_g_free0_ (gpointer var)
{
#line 200 "broker.vala"
	var = (g_free (var), NULL);
#line 1579 "broker.c"
}

static inline void
_g_slist_free__g_free0_ (GSList* self)
{
#line 199 "broker.vala"
	g_slist_free_full (self, (GDestroyNotify) _g_free0_);
#line 1587 "broker.c"
}

void
enchant_broker_load_provider_ordering (EnchantBroker* self)
{
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	GSList* conf_dirs = NULL;
	GSList* _tmp3_;
	GSList* _tmp4_;
#line 199 "broker.vala"
	g_return_if_fail (self != NULL);
#line 200 "broker.vala"
	_tmp0_ = g_str_hash;
#line 200 "broker.vala"
	_tmp1_ = g_str_equal;
#line 200 "broker.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, _g_free0_);
#line 200 "broker.vala"
	_g_hash_table_unref0 (self->provider_ordering);
#line 200 "broker.vala"
	self->provider_ordering = _tmp2_;
#line 202 "broker.vala"
	_tmp3_ = enchant_get_conf_dirs ();
#line 202 "broker.vala"
	conf_dirs = _tmp3_;
#line 203 "broker.vala"
	_tmp4_ = conf_dirs;
#line 1617 "broker.c"
	{
		GSList* dir_collection = NULL;
		GSList* dir_it = NULL;
#line 203 "broker.vala"
		dir_collection = _tmp4_;
#line 203 "broker.vala"
		for (dir_it = dir_collection; dir_it != NULL; dir_it = dir_it->next) {
#line 1625 "broker.c"
			gchar* _tmp5_;
			gchar* dir = NULL;
#line 203 "broker.vala"
			_tmp5_ = g_strdup ((const gchar*) dir_it->data);
#line 203 "broker.vala"
			dir = _tmp5_;
#line 1632 "broker.c"
			{
				gchar* ordering_file = NULL;
				const gchar* _tmp6_;
				gchar* _tmp7_;
				const gchar* _tmp8_;
#line 204 "broker.vala"
				_tmp6_ = dir;
#line 204 "broker.vala"
				_tmp7_ = g_build_filename (_tmp6_, "enchant.ordering", NULL);
#line 204 "broker.vala"
				ordering_file = _tmp7_;
#line 205 "broker.vala"
				_tmp8_ = ordering_file;
#line 205 "broker.vala"
				enchant_broker_load_ordering_from_file (self, _tmp8_);
#line 203 "broker.vala"
				_g_free0 (ordering_file);
#line 203 "broker.vala"
				_g_free0 (dir);
#line 1652 "broker.c"
			}
		}
	}
#line 199 "broker.vala"
	(conf_dirs == NULL) ? NULL : (conf_dirs = (_g_slist_free__g_free0_ (conf_dirs), NULL));
#line 1658 "broker.c"
}

GSList*
enchant_broker_get_ordered_providers (EnchantBroker* self,
                                      const gchar* tag)
{
	gchar* ordering = NULL;
	GHashTable* _tmp0_;
	gconstpointer _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	GSList* list = NULL;
	const gchar* _tmp7_;
	GSList* _tmp23_;
	GSList* result;
#line 209 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 210 "broker.vala"
	if (tag == NULL) {
#line 211 "broker.vala"
		result = NULL;
#line 211 "broker.vala"
		return result;
#line 1682 "broker.c"
	}
#line 213 "broker.vala"
	_tmp0_ = self->provider_ordering;
#line 213 "broker.vala"
	_tmp1_ = g_hash_table_lookup (_tmp0_, tag);
#line 213 "broker.vala"
	_tmp2_ = g_strdup ((const gchar*) _tmp1_);
#line 213 "broker.vala"
	ordering = _tmp2_;
#line 214 "broker.vala"
	_tmp3_ = ordering;
#line 214 "broker.vala"
	if (_tmp3_ == NULL) {
#line 1696 "broker.c"
		GHashTable* _tmp4_;
		gconstpointer _tmp5_;
		gchar* _tmp6_;
#line 215 "broker.vala"
		_tmp4_ = self->provider_ordering;
#line 215 "broker.vala"
		_tmp5_ = g_hash_table_lookup (_tmp4_, "*");
#line 215 "broker.vala"
		_tmp6_ = g_strdup ((const gchar*) _tmp5_);
#line 215 "broker.vala"
		_g_free0 (ordering);
#line 215 "broker.vala"
		ordering = _tmp6_;
#line 1710 "broker.c"
	}
#line 217 "broker.vala"
	list = NULL;
#line 219 "broker.vala"
	_tmp7_ = ordering;
#line 219 "broker.vala"
	if (_tmp7_ != NULL) {
#line 1718 "broker.c"
		gchar** tokens = NULL;
		const gchar* _tmp8_;
		gchar** _tmp9_;
		gchar** _tmp10_;
		gint tokens_length1;
		gint _tokens_size_;
		gchar** _tmp11_;
		gint _tmp11__length1;
#line 220 "broker.vala"
		_tmp8_ = ordering;
#line 220 "broker.vala"
		_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, ",", 0);
#line 220 "broker.vala"
		tokens = _tmp10_;
#line 220 "broker.vala"
		tokens_length1 = _vala_array_length (_tmp9_);
#line 220 "broker.vala"
		_tokens_size_ = tokens_length1;
#line 221 "broker.vala"
		_tmp11_ = tokens;
#line 221 "broker.vala"
		_tmp11__length1 = tokens_length1;
#line 1741 "broker.c"
		{
			gchar** token_collection = NULL;
			gint token_collection_length1 = 0;
			gint _token_collection_size_ = 0;
			gint token_it = 0;
#line 221 "broker.vala"
			token_collection = _tmp11_;
#line 221 "broker.vala"
			token_collection_length1 = _tmp11__length1;
#line 221 "broker.vala"
			for (token_it = 0; token_it < token_collection_length1; token_it = token_it + 1) {
#line 1753 "broker.c"
				const gchar* token = NULL;
#line 221 "broker.vala"
				token = token_collection[token_it];
#line 1757 "broker.c"
				{
					gchar* tok = NULL;
					const gchar* _tmp12_;
					gchar* _tmp13_;
					GSList* _tmp14_;
#line 222 "broker.vala"
					_tmp12_ = token;
#line 222 "broker.vala"
					_tmp13_ = string_strip (_tmp12_);
#line 222 "broker.vala"
					tok = _tmp13_;
#line 224 "broker.vala"
					_tmp14_ = self->provider_list;
#line 1771 "broker.c"
					{
						GSList* provider_collection = NULL;
						GSList* provider_it = NULL;
#line 224 "broker.vala"
						provider_collection = _tmp14_;
#line 224 "broker.vala"
						for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 1779 "broker.c"
							EnchantProvider* provider = NULL;
#line 224 "broker.vala"
							provider = (EnchantProvider*) provider_it->data;
#line 1783 "broker.c"
							{
								gboolean _tmp15_ = FALSE;
								EnchantProvider* _tmp16_;
#line 225 "broker.vala"
								_tmp16_ = provider;
#line 225 "broker.vala"
								if (_tmp16_ != NULL) {
#line 1791 "broker.c"
									const gchar* _tmp17_;
									EnchantProvider* _tmp18_;
									ProviderIdentify _tmp19_;
									EnchantProvider* _tmp20_;
									const gchar* _tmp21_;
#line 225 "broker.vala"
									_tmp17_ = tok;
#line 225 "broker.vala"
									_tmp18_ = provider;
#line 225 "broker.vala"
									_tmp19_ = _tmp18_->identify;
#line 225 "broker.vala"
									_tmp20_ = provider;
#line 225 "broker.vala"
									_tmp21_ = _tmp19_ (_tmp20_);
#line 225 "broker.vala"
									_tmp15_ = g_strcmp0 (_tmp17_, _tmp21_) == 0;
#line 1809 "broker.c"
								} else {
#line 225 "broker.vala"
									_tmp15_ = FALSE;
#line 1813 "broker.c"
								}
#line 225 "broker.vala"
								if (_tmp15_) {
#line 1817 "broker.c"
									EnchantProvider* _tmp22_;
#line 226 "broker.vala"
									_tmp22_ = provider;
#line 226 "broker.vala"
									list = g_slist_append (list, _tmp22_);
#line 1823 "broker.c"
								}
							}
						}
					}
#line 221 "broker.vala"
					_g_free0 (tok);
#line 1830 "broker.c"
				}
			}
		}
#line 219 "broker.vala"
		tokens = (_vala_array_free (tokens, tokens_length1, (GDestroyNotify) g_free), NULL);
#line 1836 "broker.c"
	}
#line 231 "broker.vala"
	_tmp23_ = self->provider_list;
#line 1840 "broker.c"
	{
		GSList* provider_collection = NULL;
		GSList* provider_it = NULL;
#line 231 "broker.vala"
		provider_collection = _tmp23_;
#line 231 "broker.vala"
		for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 1848 "broker.c"
			EnchantProvider* provider = NULL;
#line 231 "broker.vala"
			provider = (EnchantProvider*) provider_it->data;
#line 1852 "broker.c"
			{
				GSList* _tmp24_;
				EnchantProvider* _tmp25_;
				GSList* _tmp26_;
#line 232 "broker.vala"
				_tmp24_ = list;
#line 232 "broker.vala"
				_tmp25_ = provider;
#line 232 "broker.vala"
				_tmp26_ = g_slist_find (_tmp24_, _tmp25_);
#line 232 "broker.vala"
				if (_tmp26_ == NULL) {
#line 1865 "broker.c"
					EnchantProvider* _tmp27_;
#line 233 "broker.vala"
					_tmp27_ = provider;
#line 233 "broker.vala"
					list = g_slist_append (list, _tmp27_);
#line 1871 "broker.c"
				}
			}
		}
	}
#line 235 "broker.vala"
	result = list;
#line 235 "broker.vala"
	_g_free0 (ordering);
#line 235 "broker.vala"
	return result;
#line 1882 "broker.c"
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
#line 1622 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1623 "glib-2.0.vapi"
	result = self;
#line 1623 "glib-2.0.vapi"
	return result;
#line 1895 "broker.c"
}

EnchantDict*
enchant_broker_request_pwl_dict (EnchantBroker* self,
                                 const gchar* pwl)
{
	gboolean _tmp0_ = FALSE;
	EnchantDict* session = NULL;
	EnchantPwlDict* _tmp3_;
	EnchantPwlDict* _tmp4_;
	EnchantDict* _tmp5_;
	EnchantDict* _tmp6_;
	EnchantDict* _tmp7_;
	EnchantDict* _tmp11_;
	EnchantDict* _tmp12_;
	EnchantDict* result;
#line 238 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 240 "broker.vala"
	enchant_broker_clear_error (self);
#line 242 "broker.vala"
	if (pwl == NULL) {
#line 242 "broker.vala"
		_tmp0_ = TRUE;
#line 1920 "broker.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 242 "broker.vala"
		_tmp1_ = strlen (pwl);
#line 242 "broker.vala"
		_tmp2_ = _tmp1_;
#line 242 "broker.vala"
		_tmp0_ = _tmp2_ == 0;
#line 1930 "broker.c"
	}
#line 242 "broker.vala"
	if (_tmp0_) {
#line 243 "broker.vala"
		result = NULL;
#line 243 "broker.vala"
		return result;
#line 1938 "broker.c"
	}
#line 249 "broker.vala"
	_tmp3_ = enchant_pwl_dict_new ();
#line 249 "broker.vala"
	_tmp4_ = _tmp3_;
#line 249 "broker.vala"
	_tmp5_ = enchant_dict_with_pwl ((EnchantProviderDict*) _tmp4_, pwl, NULL);
#line 249 "broker.vala"
	_tmp6_ = _tmp5_;
#line 249 "broker.vala"
	_enchant_provider_dict_unref0 (_tmp4_);
#line 249 "broker.vala"
	session = _tmp6_;
#line 250 "broker.vala"
	_tmp7_ = session;
#line 250 "broker.vala"
	if (_tmp7_ == NULL) {
#line 1956 "broker.c"
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 251 "broker.vala"
		_tmp8_ = string_to_string (pwl);
#line 251 "broker.vala"
		_tmp9_ = g_strconcat ("Couldn't open personal wordlist '", _tmp8_, "'", NULL);
#line 251 "broker.vala"
		_tmp10_ = _tmp9_;
#line 251 "broker.vala"
		enchant_broker_set_error (self, _tmp10_);
#line 251 "broker.vala"
		_g_free0 (_tmp10_);
#line 252 "broker.vala"
		result = NULL;
#line 252 "broker.vala"
		_enchant_dict_unref0 (session);
#line 252 "broker.vala"
		return result;
#line 1976 "broker.c"
	}
#line 255 "broker.vala"
	_tmp11_ = session;
#line 255 "broker.vala"
	_tmp12_ = enchant_broker_new_dict (self, _tmp11_);
#line 255 "broker.vala"
	result = _tmp12_;
#line 255 "broker.vala"
	_enchant_dict_unref0 (session);
#line 255 "broker.vala"
	return result;
#line 1988 "broker.c"
}

static EnchantDict*
_enchant_broker_request_dict (EnchantBroker* self,
                              const gchar* tag,
                              const gchar* pwl)
{
	GSList* _tmp0_;
	EnchantDict* result;
#line 258 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 258 "broker.vala"
	g_return_val_if_fail (tag != NULL, NULL);
#line 259 "broker.vala"
	_tmp0_ = enchant_broker_get_ordered_providers (self, tag);
#line 2004 "broker.c"
	{
		GSList* provider_collection = NULL;
		GSList* provider_it = NULL;
#line 259 "broker.vala"
		provider_collection = _tmp0_;
#line 259 "broker.vala"
		for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 2012 "broker.c"
			EnchantProvider* provider = NULL;
#line 259 "broker.vala"
			provider = (EnchantProvider*) provider_it->data;
#line 2016 "broker.c"
			{
				EnchantProviderDict* dict = NULL;
				EnchantProvider* _tmp1_;
				ProviderRequestDict _tmp2_;
				EnchantProvider* _tmp3_;
				EnchantProviderDict* _tmp4_;
				EnchantProviderDict* _tmp5_;
#line 260 "broker.vala"
				_tmp1_ = provider;
#line 260 "broker.vala"
				_tmp2_ = _tmp1_->request_dict;
#line 260 "broker.vala"
				_tmp3_ = provider;
#line 260 "broker.vala"
				_tmp4_ = _tmp2_ (_tmp3_, tag);
#line 260 "broker.vala"
				dict = _tmp4_;
#line 261 "broker.vala"
				_tmp5_ = dict;
#line 261 "broker.vala"
				if (_tmp5_ != NULL) {
#line 2038 "broker.c"
					EnchantProviderDict* _tmp6_;
					EnchantDict* _tmp7_;
					EnchantDict* _tmp8_;
					EnchantDict* _tmp9_;
					EnchantDict* _tmp10_;
#line 262 "broker.vala"
					_tmp6_ = dict;
#line 262 "broker.vala"
					_tmp7_ = enchant_dict_with_implicit_pwl (_tmp6_, tag, pwl);
#line 262 "broker.vala"
					_tmp8_ = _tmp7_;
#line 262 "broker.vala"
					_tmp9_ = enchant_broker_new_dict (self, _tmp8_);
#line 262 "broker.vala"
					_tmp10_ = _tmp9_;
#line 262 "broker.vala"
					_enchant_dict_unref0 (_tmp8_);
#line 262 "broker.vala"
					result = _tmp10_;
#line 262 "broker.vala"
					_enchant_provider_dict_unref0 (dict);
#line 262 "broker.vala"
					(provider_collection == NULL) ? NULL : (provider_collection = (g_slist_free (provider_collection), NULL));
#line 262 "broker.vala"
					return result;
#line 2064 "broker.c"
				}
#line 259 "broker.vala"
				_enchant_provider_dict_unref0 (dict);
#line 2068 "broker.c"
			}
		}
#line 259 "broker.vala"
		(provider_collection == NULL) ? NULL : (provider_collection = (g_slist_free (provider_collection), NULL));
#line 2073 "broker.c"
	}
#line 265 "broker.vala"
	result = NULL;
#line 265 "broker.vala"
	return result;
#line 2079 "broker.c"
}

EnchantDict*
enchant_broker_request_dict_with_pwl (EnchantBroker* self,
                                      const gchar* composite_tag,
                                      const gchar* pwl)
{
	gboolean _tmp0_ = FALSE;
	gchar** tags = NULL;
	gchar** _tmp3_;
	gchar** _tmp4_;
	gint tags_length1;
	gint _tags_size_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	GSList* session_list = NULL;
	gchar** _tmp9_;
	gint _tmp9__length1;
	GSList* _tmp21_;
	EnchantCompositeDict* comp_dict = NULL;
	GSList* _tmp24_;
	EnchantCompositeDict* _tmp25_;
	EnchantCompositeDict* _tmp26_;
	gchar** _tmp27_;
	gint _tmp27__length1;
	const gchar* _tmp28_;
	EnchantDict* _tmp29_;
	EnchantDict* _tmp30_;
	EnchantDict* _tmp31_;
	EnchantDict* _tmp32_;
	EnchantDict* result;
#line 268 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 270 "broker.vala"
	if (composite_tag == NULL) {
#line 270 "broker.vala"
		_tmp0_ = TRUE;
#line 2117 "broker.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 270 "broker.vala"
		_tmp1_ = strlen (composite_tag);
#line 270 "broker.vala"
		_tmp2_ = _tmp1_;
#line 270 "broker.vala"
		_tmp0_ = _tmp2_ == 0;
#line 2127 "broker.c"
	}
#line 270 "broker.vala"
	if (_tmp0_) {
#line 271 "broker.vala"
		result = NULL;
#line 271 "broker.vala"
		return result;
#line 2135 "broker.c"
	}
#line 274 "broker.vala"
	_tmp4_ = _tmp3_ = g_strsplit (composite_tag, ",", 0);
#line 274 "broker.vala"
	tags = _tmp4_;
#line 274 "broker.vala"
	tags_length1 = _vala_array_length (_tmp3_);
#line 274 "broker.vala"
	_tags_size_ = tags_length1;
#line 275 "broker.vala"
	_tmp5_ = tags;
#line 275 "broker.vala"
	_tmp5__length1 = tags_length1;
#line 2149 "broker.c"
	{
		gchar** tag_collection = NULL;
		gint tag_collection_length1 = 0;
		gint _tag_collection_size_ = 0;
		gint tag_it = 0;
#line 275 "broker.vala"
		tag_collection = _tmp5_;
#line 275 "broker.vala"
		tag_collection_length1 = _tmp5__length1;
#line 275 "broker.vala"
		for (tag_it = 0; tag_it < tag_collection_length1; tag_it = tag_it + 1) {
#line 2161 "broker.c"
			const gchar* tag = NULL;
#line 275 "broker.vala"
			tag = tag_collection[tag_it];
#line 2165 "broker.c"
			{
				const gchar* _tmp6_;
				gint _tmp7_;
				gint _tmp8_;
#line 276 "broker.vala"
				_tmp6_ = tag;
#line 276 "broker.vala"
				_tmp7_ = strlen (_tmp6_);
#line 276 "broker.vala"
				_tmp8_ = _tmp7_;
#line 276 "broker.vala"
				if (_tmp8_ == 0) {
#line 277 "broker.vala"
					result = NULL;
#line 277 "broker.vala"
					tags = (_vala_array_free (tags, tags_length1, (GDestroyNotify) g_free), NULL);
#line 277 "broker.vala"
					return result;
#line 2184 "broker.c"
				}
			}
		}
	}
#line 279 "broker.vala"
	enchant_broker_clear_error (self);
#line 282 "broker.vala"
	session_list = NULL;
#line 283 "broker.vala"
	_tmp9_ = tags;
#line 283 "broker.vala"
	_tmp9__length1 = tags_length1;
#line 2197 "broker.c"
	{
		gchar** tag_collection = NULL;
		gint tag_collection_length1 = 0;
		gint _tag_collection_size_ = 0;
		gint tag_it = 0;
#line 283 "broker.vala"
		tag_collection = _tmp9_;
#line 283 "broker.vala"
		tag_collection_length1 = _tmp9__length1;
#line 283 "broker.vala"
		for (tag_it = 0; tag_it < tag_collection_length1; tag_it = tag_it + 1) {
#line 2209 "broker.c"
			const gchar* tag = NULL;
#line 283 "broker.vala"
			tag = tag_collection[tag_it];
#line 2213 "broker.c"
			{
				gchar* normalized_tag = NULL;
				const gchar* _tmp10_;
				gchar* _tmp11_;
				EnchantDict* session = NULL;
				const gchar* _tmp12_;
				EnchantDict* _tmp13_;
				EnchantDict* _tmp14_;
				EnchantDict* _tmp19_;
				EnchantDict* _tmp20_;
#line 284 "broker.vala"
				_tmp10_ = tag;
#line 284 "broker.vala"
				_tmp11_ = normalize_dictionary_tag (_tmp10_);
#line 284 "broker.vala"
				normalized_tag = _tmp11_;
#line 285 "broker.vala"
				_tmp12_ = normalized_tag;
#line 285 "broker.vala"
				_tmp13_ = _enchant_broker_request_dict (self, _tmp12_, pwl);
#line 285 "broker.vala"
				session = _tmp13_;
#line 286 "broker.vala"
				_tmp14_ = session;
#line 286 "broker.vala"
				if (_tmp14_ == NULL) {
#line 2240 "broker.c"
					const gchar* _tmp15_;
					gchar* _tmp16_;
					gchar* _tmp17_;
					EnchantDict* _tmp18_;
#line 287 "broker.vala"
					_tmp15_ = normalized_tag;
#line 287 "broker.vala"
					_tmp16_ = iso_639_from_tag (_tmp15_);
#line 287 "broker.vala"
					_tmp17_ = _tmp16_;
#line 287 "broker.vala"
					_tmp18_ = _enchant_broker_request_dict (self, _tmp17_, pwl);
#line 287 "broker.vala"
					session = _tmp18_;
#line 287 "broker.vala"
					_g_free0 (_tmp17_);
#line 2257 "broker.c"
				}
#line 288 "broker.vala"
				_tmp19_ = session;
#line 288 "broker.vala"
				if (_tmp19_ == NULL) {
#line 289 "broker.vala"
					result = NULL;
#line 289 "broker.vala"
					_g_free0 (normalized_tag);
#line 289 "broker.vala"
					(session_list == NULL) ? NULL : (session_list = (g_slist_free (session_list), NULL));
#line 289 "broker.vala"
					tags = (_vala_array_free (tags, tags_length1, (GDestroyNotify) g_free), NULL);
#line 289 "broker.vala"
					return result;
#line 2273 "broker.c"
				}
#line 290 "broker.vala"
				_tmp20_ = session;
#line 290 "broker.vala"
				session_list = g_slist_append (session_list, _tmp20_);
#line 283 "broker.vala"
				_g_free0 (normalized_tag);
#line 2281 "broker.c"
			}
		}
	}
#line 294 "broker.vala"
	_tmp21_ = session_list;
#line 294 "broker.vala"
	if (g_slist_length (_tmp21_) == ((guint) 1)) {
#line 2289 "broker.c"
		GSList* _tmp22_;
		gconstpointer _tmp23_;
#line 295 "broker.vala"
		_tmp22_ = session_list;
#line 295 "broker.vala"
		_tmp23_ = _tmp22_->data;
#line 295 "broker.vala"
		result = (EnchantDict*) _tmp23_;
#line 295 "broker.vala"
		(session_list == NULL) ? NULL : (session_list = (g_slist_free (session_list), NULL));
#line 295 "broker.vala"
		tags = (_vala_array_free (tags, tags_length1, (GDestroyNotify) g_free), NULL);
#line 295 "broker.vala"
		return result;
#line 2304 "broker.c"
	}
#line 298 "broker.vala"
	_tmp24_ = session_list;
#line 298 "broker.vala"
	session_list = NULL;
#line 298 "broker.vala"
	_tmp25_ = enchant_composite_dict_new (self, _tmp24_, composite_tag);
#line 298 "broker.vala"
	comp_dict = _tmp25_;
#line 299 "broker.vala"
	_tmp26_ = comp_dict;
#line 299 "broker.vala"
	_tmp27_ = tags;
#line 299 "broker.vala"
	_tmp27__length1 = tags_length1;
#line 299 "broker.vala"
	_tmp28_ = _tmp27_[0];
#line 299 "broker.vala"
	_tmp29_ = enchant_dict_with_implicit_pwl ((EnchantProviderDict*) _tmp26_, _tmp28_, pwl);
#line 299 "broker.vala"
	_tmp30_ = _tmp29_;
#line 299 "broker.vala"
	_tmp31_ = enchant_broker_new_dict (self, _tmp30_);
#line 299 "broker.vala"
	_tmp32_ = _tmp31_;
#line 299 "broker.vala"
	_enchant_dict_unref0 (_tmp30_);
#line 299 "broker.vala"
	result = _tmp32_;
#line 299 "broker.vala"
	_enchant_provider_dict_unref0 (comp_dict);
#line 299 "broker.vala"
	(session_list == NULL) ? NULL : (session_list = (g_slist_free (session_list), NULL));
#line 299 "broker.vala"
	tags = (_vala_array_free (tags, tags_length1, (GDestroyNotify) g_free), NULL);
#line 299 "broker.vala"
	return result;
#line 2342 "broker.c"
}

EnchantDict*
enchant_broker_request_dict (EnchantBroker* self,
                             const gchar* tag)
{
	EnchantDict* _tmp0_;
	EnchantDict* result;
#line 302 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 303 "broker.vala"
	_tmp0_ = enchant_broker_request_dict_with_pwl (self, tag, NULL);
#line 303 "broker.vala"
	result = _tmp0_;
#line 303 "broker.vala"
	return result;
#line 2359 "broker.c"
}

void
enchant_broker_describe (EnchantBroker* self,
                         EnchantBrokerDescribeFn fn,
                         void* user_data)
{
	GSList* _tmp0_;
#line 306 "broker.vala"
	g_return_if_fail (self != NULL);
#line 308 "broker.vala"
	enchant_broker_clear_error (self);
#line 310 "broker.vala"
	if (fn == NULL) {
#line 311 "broker.vala"
		return;
#line 2376 "broker.c"
	}
#line 313 "broker.vala"
	_tmp0_ = self->provider_list;
#line 2380 "broker.c"
	{
		GSList* provider_collection = NULL;
		GSList* provider_it = NULL;
#line 313 "broker.vala"
		provider_collection = _tmp0_;
#line 313 "broker.vala"
		for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 2388 "broker.c"
			EnchantProvider* provider = NULL;
#line 313 "broker.vala"
			provider = (EnchantProvider*) provider_it->data;
#line 2392 "broker.c"
			{
				gchar* name = NULL;
				EnchantProvider* _tmp1_;
				ProviderIdentify _tmp2_;
				EnchantProvider* _tmp3_;
				const gchar* _tmp4_;
				gchar* _tmp5_;
				gchar* desc = NULL;
				EnchantProvider* _tmp6_;
				ProviderDescribe _tmp7_;
				EnchantProvider* _tmp8_;
				const gchar* _tmp9_;
				gchar* _tmp10_;
				gchar* file = NULL;
				EnchantProvider* _tmp11_;
				GModule* _tmp12_;
				const gchar* _tmp13_;
				gchar* _tmp14_;
				const gchar* _tmp15_;
				const gchar* _tmp16_;
				const gchar* _tmp17_;
#line 314 "broker.vala"
				_tmp1_ = provider;
#line 314 "broker.vala"
				_tmp2_ = _tmp1_->identify;
#line 314 "broker.vala"
				_tmp3_ = provider;
#line 314 "broker.vala"
				_tmp4_ = _tmp2_ (_tmp3_);
#line 314 "broker.vala"
				_tmp5_ = g_strdup (_tmp4_);
#line 314 "broker.vala"
				name = _tmp5_;
#line 315 "broker.vala"
				_tmp6_ = provider;
#line 315 "broker.vala"
				_tmp7_ = _tmp6_->describe;
#line 315 "broker.vala"
				_tmp8_ = provider;
#line 315 "broker.vala"
				_tmp9_ = _tmp7_ (_tmp8_);
#line 315 "broker.vala"
				_tmp10_ = g_strdup (_tmp9_);
#line 315 "broker.vala"
				desc = _tmp10_;
#line 316 "broker.vala"
				_tmp11_ = provider;
#line 316 "broker.vala"
				_tmp12_ = _tmp11_->module;
#line 316 "broker.vala"
				_tmp13_ = g_module_name (_tmp12_);
#line 316 "broker.vala"
				_tmp14_ = g_strdup (_tmp13_);
#line 316 "broker.vala"
				file = _tmp14_;
#line 318 "broker.vala"
				_tmp15_ = name;
#line 318 "broker.vala"
				_tmp16_ = desc;
#line 318 "broker.vala"
				_tmp17_ = file;
#line 318 "broker.vala"
				fn (_tmp15_, _tmp16_, _tmp17_, user_data);
#line 313 "broker.vala"
				_g_free0 (file);
#line 313 "broker.vala"
				_g_free0 (desc);
#line 313 "broker.vala"
				_g_free0 (name);
#line 2462 "broker.c"
			}
		}
	}
}

void
enchant_broker_list_dicts (EnchantBroker* self,
                           EnchantDictDescribeFn fn,
                           void* user_data)
{
	GHashTable* tag_map = NULL;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	GSList* _tmp3_;
	GSList* _tmp4_;
	GSList* tags = NULL;
	GHashTable* _tmp38_;
	GList* _tmp39_;
	GSList* _tmp44_;
#line 322 "broker.vala"
	g_return_if_fail (self != NULL);
#line 324 "broker.vala"
	if (fn == NULL) {
#line 325 "broker.vala"
		return;
#line 2489 "broker.c"
	}
#line 327 "broker.vala"
	_tmp0_ = g_str_hash;
#line 327 "broker.vala"
	_tmp1_ = g_str_equal;
#line 327 "broker.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, NULL);
#line 327 "broker.vala"
	tag_map = _tmp2_;
#line 329 "broker.vala"
	enchant_broker_clear_error (self);
#line 330 "broker.vala"
	g_debug ("broker.vala:330: listing dictionaries");
#line 331 "broker.vala"
	_tmp3_ = self->provider_list;
#line 331 "broker.vala"
	if (_tmp3_ == NULL) {
#line 332 "broker.vala"
		g_debug ("broker.vala:332: no providers found!");
#line 2509 "broker.c"
	}
#line 334 "broker.vala"
	_tmp4_ = self->provider_list;
#line 2513 "broker.c"
	{
		GSList* provider_collection = NULL;
		GSList* provider_it = NULL;
#line 334 "broker.vala"
		provider_collection = _tmp4_;
#line 334 "broker.vala"
		for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 2521 "broker.c"
			EnchantProvider* provider = NULL;
#line 334 "broker.vala"
			provider = (EnchantProvider*) provider_it->data;
#line 2525 "broker.c"
			{
				EnchantProvider* _tmp5_;
				ProviderDescribe _tmp6_;
				EnchantProvider* _tmp7_;
				const gchar* _tmp8_;
				EnchantProvider* _tmp9_;
				ProviderListDicts _tmp10_;
				EnchantProvider* _tmp11_;
				size_t _tmp12_ = 0;
				gchar** _tmp13_;
#line 335 "broker.vala"
				_tmp5_ = provider;
#line 335 "broker.vala"
				_tmp6_ = _tmp5_->describe;
#line 335 "broker.vala"
				_tmp7_ = provider;
#line 335 "broker.vala"
				_tmp8_ = _tmp6_ (_tmp7_);
#line 335 "broker.vala"
				g_debug ("broker.vala:335: provider %s", _tmp8_);
#line 337 "broker.vala"
				_tmp9_ = provider;
#line 337 "broker.vala"
				_tmp10_ = _tmp9_->list_dicts;
#line 337 "broker.vala"
				_tmp11_ = provider;
#line 337 "broker.vala"
				_tmp13_ = _tmp10_ (_tmp11_, &_tmp12_);
#line 2554 "broker.c"
				{
					gchar** tag_collection = NULL;
					gint tag_collection_length1 = 0;
					gint _tag_collection_size_ = 0;
					gint tag_it = 0;
#line 337 "broker.vala"
					tag_collection = _tmp13_;
#line 337 "broker.vala"
					tag_collection_length1 = _tmp12_;
#line 337 "broker.vala"
					for (tag_it = 0; tag_it < tag_collection_length1; tag_it = tag_it + 1) {
#line 2566 "broker.c"
						gchar* _tmp14_;
						gchar* tag = NULL;
#line 337 "broker.vala"
						_tmp14_ = g_strdup (tag_collection[tag_it]);
#line 337 "broker.vala"
						tag = _tmp14_;
#line 2573 "broker.c"
						{
							const gchar* _tmp15_;
							const gchar* _tmp23_;
							GSList* providers = NULL;
							const gchar* _tmp24_;
							GSList* _tmp25_;
							gint this_priority = 0;
							GSList* _tmp26_;
							EnchantProvider* _tmp27_;
#line 338 "broker.vala"
							_tmp15_ = tag;
#line 338 "broker.vala"
							if (_tmp15_ == NULL) {
#line 2587 "broker.c"
								EnchantProvider* _tmp16_;
								ProviderIdentify _tmp17_;
								EnchantProvider* _tmp18_;
								const gchar* _tmp19_;
								const gchar* _tmp20_;
								gchar* _tmp21_;
								gchar* _tmp22_;
#line 339 "broker.vala"
								_tmp16_ = provider;
#line 339 "broker.vala"
								_tmp17_ = _tmp16_->identify;
#line 339 "broker.vala"
								_tmp18_ = provider;
#line 339 "broker.vala"
								_tmp19_ = _tmp17_ (_tmp18_);
#line 339 "broker.vala"
								_tmp20_ = string_to_string (_tmp19_);
#line 339 "broker.vala"
								_tmp21_ = g_strconcat ("null entry in dictionaries returned by ", _tmp20_, NULL);
#line 339 "broker.vala"
								_tmp22_ = _tmp21_;
#line 339 "broker.vala"
								enchant_broker_set_error (self, _tmp22_);
#line 339 "broker.vala"
								_g_free0 (_tmp22_);
#line 340 "broker.vala"
								_g_free0 (tag);
#line 340 "broker.vala"
								continue;
#line 2617 "broker.c"
							}
#line 342 "broker.vala"
							_tmp23_ = tag;
#line 342 "broker.vala"
							g_debug ("broker.vala:342: tag %s", _tmp23_);
#line 343 "broker.vala"
							_tmp24_ = tag;
#line 343 "broker.vala"
							_tmp25_ = enchant_broker_get_ordered_providers (self, _tmp24_);
#line 343 "broker.vala"
							providers = _tmp25_;
#line 344 "broker.vala"
							_tmp26_ = providers;
#line 344 "broker.vala"
							_tmp27_ = provider;
#line 344 "broker.vala"
							this_priority = g_slist_index (_tmp26_, _tmp27_);
#line 345 "broker.vala"
							g_debug ("broker.vala:345: priority %d", this_priority);
#line 346 "broker.vala"
							if (this_priority != -1) {
#line 2639 "broker.c"
								gint min_priority = 0;
								EnchantProvider* prov = NULL;
								GHashTable* _tmp28_;
								const gchar* _tmp29_;
								gconstpointer _tmp30_;
								EnchantProvider* _tmp31_;
#line 347 "broker.vala"
								min_priority = this_priority + 1;
#line 348 "broker.vala"
								_tmp28_ = tag_map;
#line 348 "broker.vala"
								_tmp29_ = tag;
#line 348 "broker.vala"
								_tmp30_ = g_hash_table_lookup (_tmp28_, _tmp29_);
#line 348 "broker.vala"
								prov = (EnchantProvider*) _tmp30_;
#line 349 "broker.vala"
								_tmp31_ = prov;
#line 349 "broker.vala"
								if (_tmp31_ != NULL) {
#line 2660 "broker.c"
									GSList* _tmp32_;
									EnchantProvider* _tmp33_;
#line 350 "broker.vala"
									_tmp32_ = providers;
#line 350 "broker.vala"
									_tmp33_ = prov;
#line 350 "broker.vala"
									min_priority = g_slist_index (_tmp32_, _tmp33_);
#line 2669 "broker.c"
								}
#line 351 "broker.vala"
								if (this_priority < min_priority) {
#line 2673 "broker.c"
									GHashTable* _tmp34_;
									const gchar* _tmp35_;
									gchar* _tmp36_;
									EnchantProvider* _tmp37_;
#line 352 "broker.vala"
									_tmp34_ = tag_map;
#line 352 "broker.vala"
									_tmp35_ = tag;
#line 352 "broker.vala"
									_tmp36_ = g_strdup (_tmp35_);
#line 352 "broker.vala"
									_tmp37_ = provider;
#line 352 "broker.vala"
									g_hash_table_insert (_tmp34_, _tmp36_, _tmp37_);
#line 2688 "broker.c"
								}
							}
#line 337 "broker.vala"
							(providers == NULL) ? NULL : (providers = (g_slist_free (providers), NULL));
#line 337 "broker.vala"
							_g_free0 (tag);
#line 2695 "broker.c"
						}
					}
#line 337 "broker.vala"
					tag_collection = (_vala_array_free (tag_collection, tag_collection_length1, (GDestroyNotify) g_free), NULL);
#line 2700 "broker.c"
				}
			}
		}
	}
#line 357 "broker.vala"
	tags = NULL;
#line 358 "broker.vala"
	_tmp38_ = tag_map;
#line 358 "broker.vala"
	_tmp39_ = g_hash_table_get_keys (_tmp38_);
#line 2711 "broker.c"
	{
		GList* key_collection = NULL;
		GList* key_it = NULL;
#line 358 "broker.vala"
		key_collection = _tmp39_;
#line 358 "broker.vala"
		for (key_it = key_collection; key_it != NULL; key_it = key_it->next) {
#line 2719 "broker.c"
			gchar* _tmp40_;
			gchar* key = NULL;
#line 358 "broker.vala"
			_tmp40_ = g_strdup ((const gchar*) key_it->data);
#line 358 "broker.vala"
			key = _tmp40_;
#line 2726 "broker.c"
			{
				const gchar* _tmp41_;
				gchar* _tmp42_;
				GCompareFunc _tmp43_;
#line 359 "broker.vala"
				_tmp41_ = key;
#line 359 "broker.vala"
				_tmp42_ = g_strdup (_tmp41_);
#line 359 "broker.vala"
				_tmp43_ = ((GCompareFunc) g_strcmp0);
#line 359 "broker.vala"
				tags = g_slist_insert_sorted (tags, _tmp42_, _tmp43_);
#line 358 "broker.vala"
				_g_free0 (key);
#line 2741 "broker.c"
			}
		}
#line 358 "broker.vala"
		(key_collection == NULL) ? NULL : (key_collection = (g_list_free (key_collection), NULL));
#line 2746 "broker.c"
	}
#line 361 "broker.vala"
	_tmp44_ = tags;
#line 2750 "broker.c"
	{
		GSList* tag_collection = NULL;
		GSList* tag_it = NULL;
#line 361 "broker.vala"
		tag_collection = _tmp44_;
#line 361 "broker.vala"
		for (tag_it = tag_collection; tag_it != NULL; tag_it = tag_it->next) {
#line 2758 "broker.c"
			gchar* _tmp45_;
			gchar* tag = NULL;
#line 361 "broker.vala"
			_tmp45_ = g_strdup ((const gchar*) tag_it->data);
#line 361 "broker.vala"
			tag = _tmp45_;
#line 2765 "broker.c"
			{
				EnchantProvider* provider = NULL;
				GHashTable* _tmp46_;
				const gchar* _tmp47_;
				gconstpointer _tmp48_;
				gchar* name = NULL;
				EnchantProvider* _tmp49_;
				ProviderIdentify _tmp50_;
				EnchantProvider* _tmp51_;
				const gchar* _tmp52_;
				gchar* _tmp53_;
				gchar* desc = NULL;
				EnchantProvider* _tmp54_;
				ProviderDescribe _tmp55_;
				EnchantProvider* _tmp56_;
				const gchar* _tmp57_;
				gchar* _tmp58_;
				gchar* file = NULL;
				EnchantProvider* _tmp59_;
				GModule* _tmp60_;
				const gchar* _tmp61_;
				gchar* _tmp62_;
				const gchar* _tmp63_;
				const gchar* _tmp64_;
				const gchar* _tmp65_;
				const gchar* _tmp66_;
#line 362 "broker.vala"
				_tmp46_ = tag_map;
#line 362 "broker.vala"
				_tmp47_ = tag;
#line 362 "broker.vala"
				_tmp48_ = g_hash_table_lookup (_tmp46_, _tmp47_);
#line 362 "broker.vala"
				provider = (EnchantProvider*) _tmp48_;
#line 363 "broker.vala"
				_tmp49_ = provider;
#line 363 "broker.vala"
				_tmp50_ = _tmp49_->identify;
#line 363 "broker.vala"
				_tmp51_ = provider;
#line 363 "broker.vala"
				_tmp52_ = _tmp50_ (_tmp51_);
#line 363 "broker.vala"
				_tmp53_ = g_strdup (_tmp52_);
#line 363 "broker.vala"
				name = _tmp53_;
#line 364 "broker.vala"
				_tmp54_ = provider;
#line 364 "broker.vala"
				_tmp55_ = _tmp54_->describe;
#line 364 "broker.vala"
				_tmp56_ = provider;
#line 364 "broker.vala"
				_tmp57_ = _tmp55_ (_tmp56_);
#line 364 "broker.vala"
				_tmp58_ = g_strdup (_tmp57_);
#line 364 "broker.vala"
				desc = _tmp58_;
#line 365 "broker.vala"
				_tmp59_ = provider;
#line 365 "broker.vala"
				_tmp60_ = _tmp59_->module;
#line 365 "broker.vala"
				_tmp61_ = g_module_name (_tmp60_);
#line 365 "broker.vala"
				_tmp62_ = g_strdup (_tmp61_);
#line 365 "broker.vala"
				file = _tmp62_;
#line 366 "broker.vala"
				_tmp63_ = tag;
#line 366 "broker.vala"
				_tmp64_ = name;
#line 366 "broker.vala"
				_tmp65_ = desc;
#line 366 "broker.vala"
				_tmp66_ = file;
#line 366 "broker.vala"
				fn (_tmp63_, _tmp64_, _tmp65_, _tmp66_, user_data);
#line 361 "broker.vala"
				_g_free0 (file);
#line 361 "broker.vala"
				_g_free0 (desc);
#line 361 "broker.vala"
				_g_free0 (name);
#line 361 "broker.vala"
				_g_free0 (tag);
#line 2852 "broker.c"
			}
		}
	}
#line 322 "broker.vala"
	(tags == NULL) ? NULL : (tags = (_g_slist_free__g_free0_ (tags), NULL));
#line 322 "broker.vala"
	_g_hash_table_unref0 (tag_map);
#line 2860 "broker.c"
}

static gint
_enchant_broker_dict_exists (EnchantBroker* self,
                             const gchar* tag)
{
	GSList* _tmp0_;
	gint result;
#line 370 "broker.vala"
	g_return_val_if_fail (self != NULL, -1);
#line 370 "broker.vala"
	g_return_val_if_fail (tag != NULL, -1);
#line 372 "broker.vala"
	_tmp0_ = self->provider_list;
#line 2875 "broker.c"
	{
		GSList* provider_collection = NULL;
		GSList* provider_it = NULL;
#line 372 "broker.vala"
		provider_collection = _tmp0_;
#line 372 "broker.vala"
		for (provider_it = provider_collection; provider_it != NULL; provider_it = provider_it->next) {
#line 2883 "broker.c"
			EnchantProvider* provider = NULL;
#line 372 "broker.vala"
			provider = (EnchantProvider*) provider_it->data;
#line 2887 "broker.c"
			{
				EnchantProvider* _tmp1_;
#line 373 "broker.vala"
				_tmp1_ = provider;
#line 373 "broker.vala"
				if (_enchant_provider_dictionary_exists (_tmp1_, tag) != 0) {
#line 374 "broker.vala"
					result = 1;
#line 374 "broker.vala"
					return result;
#line 2898 "broker.c"
				}
			}
		}
	}
#line 375 "broker.vala"
	result = 0;
#line 375 "broker.vala"
	return result;
#line 2907 "broker.c"
}

gint
enchant_broker_dict_exists (EnchantBroker* self,
                            const gchar* tag)
{
	gboolean _tmp0_ = FALSE;
	gchar* normalized_tag = NULL;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gint exists = 0;
	const gchar* _tmp7_;
	gint result;
#line 378 "broker.vala"
	g_return_val_if_fail (self != NULL, -1);
#line 380 "broker.vala"
	enchant_broker_clear_error (self);
#line 382 "broker.vala"
	if (tag == NULL) {
#line 382 "broker.vala"
		_tmp0_ = TRUE;
#line 2931 "broker.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 382 "broker.vala"
		_tmp1_ = strlen (tag);
#line 382 "broker.vala"
		_tmp2_ = _tmp1_;
#line 382 "broker.vala"
		_tmp0_ = _tmp2_ == 0;
#line 2941 "broker.c"
	}
#line 382 "broker.vala"
	if (_tmp0_) {
#line 383 "broker.vala"
		result = 0;
#line 383 "broker.vala"
		return result;
#line 2949 "broker.c"
	}
#line 385 "broker.vala"
	_tmp3_ = normalize_dictionary_tag (tag);
#line 385 "broker.vala"
	normalized_tag = _tmp3_;
#line 386 "broker.vala"
	_tmp4_ = normalized_tag;
#line 386 "broker.vala"
	_tmp5_ = strlen (_tmp4_);
#line 386 "broker.vala"
	_tmp6_ = _tmp5_;
#line 386 "broker.vala"
	if (_tmp6_ == 0) {
#line 387 "broker.vala"
		result = 0;
#line 387 "broker.vala"
		_g_free0 (normalized_tag);
#line 387 "broker.vala"
		return result;
#line 2969 "broker.c"
	}
#line 388 "broker.vala"
	exists = 0;
#line 390 "broker.vala"
	_tmp7_ = normalized_tag;
#line 390 "broker.vala"
	exists = _enchant_broker_dict_exists (self, _tmp7_);
#line 390 "broker.vala"
	if (exists == 0) {
#line 2979 "broker.c"
		gchar* iso_639_only_tag = NULL;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
#line 391 "broker.vala"
		_tmp8_ = normalized_tag;
#line 391 "broker.vala"
		_tmp9_ = iso_639_from_tag (_tmp8_);
#line 391 "broker.vala"
		iso_639_only_tag = _tmp9_;
#line 392 "broker.vala"
		_tmp10_ = iso_639_only_tag;
#line 392 "broker.vala"
		if (_tmp10_ == NULL) {
#line 393 "broker.vala"
			result = 0;
#line 393 "broker.vala"
			_g_free0 (iso_639_only_tag);
#line 393 "broker.vala"
			_g_free0 (normalized_tag);
#line 393 "broker.vala"
			return result;
#line 3004 "broker.c"
		}
#line 395 "broker.vala"
		_tmp11_ = normalized_tag;
#line 395 "broker.vala"
		_tmp12_ = iso_639_only_tag;
#line 395 "broker.vala"
		if (g_strcmp0 (_tmp11_, _tmp12_) != 0) {
#line 3012 "broker.c"
			const gchar* _tmp13_;
#line 396 "broker.vala"
			_tmp13_ = iso_639_only_tag;
#line 396 "broker.vala"
			exists = _enchant_broker_dict_exists (self, _tmp13_);
#line 3018 "broker.c"
		}
#line 390 "broker.vala"
		_g_free0 (iso_639_only_tag);
#line 3022 "broker.c"
	}
#line 399 "broker.vala"
	result = exists;
#line 399 "broker.vala"
	_g_free0 (normalized_tag);
#line 399 "broker.vala"
	return result;
#line 3030 "broker.c"
}

static gpointer
_enchant_dict_ref0 (gpointer self)
{
#line 405 "broker.vala"
	return self ? enchant_dict_ref (self) : NULL;
#line 3038 "broker.c"
}

EnchantDict*
enchant_broker_new_dict (EnchantBroker* self,
                         EnchantDict* session)
{
	GHashTable* _tmp0_;
	EnchantDict* _tmp1_;
	EnchantDict* session_ref = NULL;
	EnchantDict* _tmp2_;
	EnchantDict* result;
#line 402 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 403 "broker.vala"
	if (session == NULL) {
#line 404 "broker.vala"
		result = NULL;
#line 404 "broker.vala"
		return result;
#line 3058 "broker.c"
	}
#line 405 "broker.vala"
	_tmp0_ = self->sessions;
#line 405 "broker.vala"
	_tmp1_ = _enchant_dict_ref0 (session);
#line 405 "broker.vala"
	g_hash_table_add (_tmp0_, _tmp1_);
#line 406 "broker.vala"
	session_ref = session;
#line 407 "broker.vala"
	_tmp2_ = session_ref;
#line 407 "broker.vala"
	result = _tmp2_;
#line 407 "broker.vala"
	return result;
#line 3074 "broker.c"
}

void
enchant_broker_free_dict (EnchantBroker* self,
                          EnchantDict* session)
{
	GHashTable* _tmp0_;
#line 410 "broker.vala"
	g_return_if_fail (self != NULL);
#line 411 "broker.vala"
	if (session == NULL) {
#line 412 "broker.vala"
		return;
#line 3088 "broker.c"
	}
#line 413 "broker.vala"
	_tmp0_ = self->sessions;
#line 413 "broker.vala"
	g_hash_table_remove (_tmp0_, session);
#line 414 "broker.vala"
	enchant_broker_clear_error (self);
#line 3096 "broker.c"
}

const gchar*
enchant_broker_get_error (EnchantBroker* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 104 "broker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 104 "broker.vala"
	_tmp0_ = self->_error;
#line 104 "broker.vala"
	result = _tmp0_;
#line 104 "broker.vala"
	return result;
#line 3112 "broker.c"
}

void
enchant_broker_set_error (EnchantBroker* self,
                          const gchar* value)
{
	gchar* _tmp0_;
#line 105 "broker.vala"
	g_return_if_fail (self != NULL);
#line 105 "broker.vala"
	_tmp0_ = g_strdup (value);
#line 105 "broker.vala"
	_g_free0 (self->_error);
#line 105 "broker.vala"
	self->_error = _tmp0_;
#line 3128 "broker.c"
}

static void
enchant_broker_instance_init (EnchantBroker * self)
{
}

void
enchant_broker_free (EnchantBroker * self)
{
#line 96 "broker.vala"
	g_return_if_fail (self != NULL);
#line 77 "broker.vala"
	(self->provider_list == NULL) ? NULL : (self->provider_list = (_g_slist_free__enchant_provider_unref0_ (self->provider_list), NULL));
#line 78 "broker.vala"
	_g_hash_table_unref0 (self->provider_ordering);
#line 79 "broker.vala"
	_g_hash_table_unref0 (self->sessions);
#line 81 "broker.vala"
	_g_free0 (self->_error);
#line 76 "broker.vala"
	g_slice_free (EnchantBroker, self);
#line 3151 "broker.c"
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

