/* pwl.c generated by valac 0.56.19, the Vala compiler
 * generated from pwl.vala, do not modify */

/* libenchant: Personal word lists
 * Copyright (C) 2003, 2004 Dom Lachowicz
 * Copyright (C) 2016-2026 Reuben Thomas <rrt@sc3d.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along along with this program; if not, see
 * <https://www.gnu.org/licenses/>.
 *
 * In addition, as a special exception, the copyright holders
 * give permission to link the code of this program with
 * non-LGPL Spelling Provider libraries (eg: a MSFT Office
 * spell checker backend) and distribute linked combinations including
 * the two.  You must obey the GNU Lesser General Public License in all
 * respects for all of the code used other than said providers.  If you modify
 * this file, you may extend this exception to your version of the
 * file, but you are not obligated to do so.  If you do not wish to
 * do so, delete this exception statement from your version.
 */

#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <time.h>
#include <sys/types.h>
#include <glib/gstdio.h>
#include <sys/stat.h>
#include <gobject/gvaluecollector.h>

#define BOM ((gunichar) 0xfeff)
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_ENCHANT_PWL (enchant_pwl_get_type ())
#define ENCHANT_PWL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PWL, EnchantPWL))
#define ENCHANT_PWL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PWL, EnchantPWLClass))
#define IS_ENCHANT_PWL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PWL))
#define IS_ENCHANT_PWL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PWL))
#define ENCHANT_PWL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PWL, EnchantPWLClass))

typedef struct _EnchantPWL EnchantPWL;
typedef struct _EnchantPWLClass EnchantPWLClass;
typedef struct _EnchantPWLPrivate EnchantPWLPrivate;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))

#define TYPE_ENCHANT_DICT (enchant_dict_get_type ())
#define ENCHANT_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_DICT, EnchantDict))
#define ENCHANT_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_DICT, EnchantDictClass))
#define IS_ENCHANT_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_DICT))
#define IS_ENCHANT_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_DICT))
#define ENCHANT_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_DICT, EnchantDictClass))

typedef struct _EnchantDict EnchantDict;
typedef struct _EnchantDictClass EnchantDictClass;
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
typedef struct _ParamSpecEnchantPWL ParamSpecEnchantPWL;

#define TYPE_ENCHANT_PROVIDER_DICT (enchant_provider_dict_get_type ())
#define ENCHANT_PROVIDER_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDict))
#define ENCHANT_PROVIDER_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDictClass))
#define IS_ENCHANT_PROVIDER_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PROVIDER_DICT))
#define IS_ENCHANT_PROVIDER_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PROVIDER_DICT))
#define ENCHANT_PROVIDER_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PROVIDER_DICT, EnchantProviderDictClass))

typedef struct _EnchantProviderDict EnchantProviderDict;
typedef struct _EnchantProviderDictClass EnchantProviderDictClass;
typedef struct _EnchantProviderDictPrivate EnchantProviderDictPrivate;

#define TYPE_ENCHANT_PROVIDER (enchant_provider_get_type ())
#define ENCHANT_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PROVIDER, EnchantProvider))
#define ENCHANT_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PROVIDER, EnchantProviderClass))
#define IS_ENCHANT_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PROVIDER))
#define IS_ENCHANT_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PROVIDER))
#define ENCHANT_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PROVIDER, EnchantProviderClass))

typedef struct _EnchantProvider EnchantProvider;
typedef struct _EnchantProviderClass EnchantProviderClass;
typedef gint (*DictCheck) (EnchantProviderDict* me, const gchar* word, size_t len);
typedef gchar** (*DictSuggest) (EnchantProviderDict* me, const gchar* word, size_t len, size_t* result_length1);
typedef void (*DictAddToSession) (EnchantProviderDict* me, const gchar* word, size_t len);
typedef void (*DictRemoveFromSession) (EnchantProviderDict* me, const gchar* word, size_t len);
typedef const gchar* (*DictGetExtraWordCharacters) (EnchantProviderDict* me);
typedef gint (*DictIsWordCharacter) (EnchantProviderDict* me, guint32 uc_in, size_t n);

#define TYPE_ENCHANT_PWL_DICT (enchant_pwl_dict_get_type ())
#define ENCHANT_PWL_DICT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCHANT_PWL_DICT, EnchantPwlDict))
#define ENCHANT_PWL_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENCHANT_PWL_DICT, EnchantPwlDictClass))
#define IS_ENCHANT_PWL_DICT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCHANT_PWL_DICT))
#define IS_ENCHANT_PWL_DICT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENCHANT_PWL_DICT))
#define ENCHANT_PWL_DICT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENCHANT_PWL_DICT, EnchantPwlDictClass))

typedef struct _EnchantPwlDict EnchantPwlDict;
typedef struct _EnchantPwlDictClass EnchantPwlDictClass;
typedef struct _EnchantPwlDictPrivate EnchantPwlDictPrivate;

struct _EnchantPWL {
	GTypeInstance parent_instance;
	volatile int ref_count;
	EnchantPWLPrivate * priv;
};

struct _EnchantPWLClass {
	GTypeClass parent_class;
	void (*finalize) (EnchantPWL *self);
};

struct _EnchantPWLPrivate {
	gchar* filename;
	gboolean exclude;
	time_t file_changed;
	GHashTable* words;
};

struct _ParamSpecEnchantPWL {
	GParamSpec parent_instance;
};

struct _EnchantProviderDict {
	GTypeInstance parent_instance;
	volatile int ref_count;
	EnchantProviderDictPrivate * priv;
	void* user_data;
	EnchantProvider* provider;
	gchar* language_tag;
	gchar* error;
	DictCheck check_method;
	DictSuggest suggest_method;
	DictAddToSession add_to_session_method;
	DictRemoveFromSession remove_from_session_method;
	DictGetExtraWordCharacters get_extra_word_characters_method;
	DictIsWordCharacter is_word_character_method;
};

struct _EnchantProviderDictClass {
	GTypeClass parent_class;
	void (*finalize) (EnchantProviderDict *self);
};

struct _EnchantPwlDict {
	EnchantProviderDict parent_instance;
	EnchantPwlDictPrivate * priv;
};

struct _EnchantPwlDictClass {
	EnchantProviderDictClass parent_class;
};

static gint EnchantPWL_private_offset;
static gpointer enchant_pwl_parent_class = NULL;
static gpointer enchant_pwl_dict_parent_class = NULL;

VALA_EXTERN void lock_file (FILE* f);
VALA_EXTERN void unlock_file (FILE* f);
VALA_EXTERN gchar* utf8_strtitle (const gchar* str);
VALA_EXTERN gboolean is_all_caps (const gchar* word);
VALA_EXTERN gboolean is_title_case (const gchar* word);
VALA_EXTERN gpointer enchant_pwl_ref (gpointer instance);
VALA_EXTERN void enchant_pwl_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_pwl (const gchar* name,
                                    const gchar* nick,
                                    const gchar* blurb,
                                    GType object_type,
                                    GParamFlags flags);
VALA_EXTERN void value_set_enchant_pwl (GValue* value,
                            gpointer v_object);
VALA_EXTERN void value_take_enchant_pwl (GValue* value,
                             gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_pwl (const GValue* value);
VALA_EXTERN GType enchant_pwl_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantPWL, enchant_pwl_unref)
static void _g_free0_ (gpointer var);
VALA_EXTERN EnchantPWL* enchant_pwl_new (const gchar* filename,
                             gboolean exclude);
VALA_EXTERN EnchantPWL* enchant_pwl_construct (GType object_type,
                                   const gchar* filename,
                                   gboolean exclude);
static void enchant_pwl_add_to_table (EnchantPWL* self,
                               const gchar* word);
VALA_EXTERN gpointer enchant_dict_ref (gpointer instance);
VALA_EXTERN void enchant_dict_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_dict (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void value_set_enchant_dict (GValue* value,
                             gpointer v_object);
VALA_EXTERN void value_take_enchant_dict (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_dict (const GValue* value);
VALA_EXTERN GType enchant_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantDict, enchant_dict_unref)
VALA_EXTERN void enchant_pwl_add (EnchantPWL* self,
                      EnchantDict* session,
                      const gchar* word_buf,
                      ssize_t len);
VALA_EXTERN gchar* buf_to_utf8_string (const gchar* str_buf,
                           gssize len);
static void enchant_pwl_refresh_from_file (EnchantPWL* self,
                                    EnchantDict* session);
VALA_EXTERN void enchant_pwl_remove (EnchantPWL* self,
                         EnchantDict* session,
                         const gchar* word_buf,
                         ssize_t len);
VALA_EXTERN gint enchant_pwl_check (EnchantPWL* self,
                        EnchantDict* session,
                        const gchar* word_buf,
                        ssize_t len);
VALA_EXTERN void enchant_dict_remove_from_session (EnchantDict* self,
                                       const gchar* word_buf,
                                       ssize_t len);
VALA_EXTERN void enchant_dict_add_to_session (EnchantDict* self,
                                  const gchar* word_buf,
                                  ssize_t len);
static void enchant_pwl_finalize (EnchantPWL * obj);
static GType enchant_pwl_get_type_once (void);
VALA_EXTERN gpointer enchant_provider_dict_ref (gpointer instance);
VALA_EXTERN void enchant_provider_dict_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_provider_dict (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
VALA_EXTERN void value_set_enchant_provider_dict (GValue* value,
                                      gpointer v_object);
VALA_EXTERN void value_take_enchant_provider_dict (GValue* value,
                                       gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_provider_dict (const GValue* value);
VALA_EXTERN GType enchant_provider_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantProviderDict, enchant_provider_dict_unref)
VALA_EXTERN gint check_impl (EnchantProviderDict* me,
                 const gchar* word,
                 size_t len);
VALA_EXTERN gchar** suggest_impl (EnchantProviderDict* me,
                      const gchar* word,
                      size_t len,
                      size_t* result_length1);
VALA_EXTERN gpointer enchant_provider_ref (gpointer instance);
VALA_EXTERN void enchant_provider_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_enchant_provider (const gchar* name,
                                         const gchar* nick,
                                         const gchar* blurb,
                                         GType object_type,
                                         GParamFlags flags);
VALA_EXTERN void value_set_enchant_provider (GValue* value,
                                 gpointer v_object);
VALA_EXTERN void value_take_enchant_provider (GValue* value,
                                  gpointer v_object);
VALA_EXTERN gpointer value_get_enchant_provider (const GValue* value);
VALA_EXTERN GType enchant_provider_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantProvider, enchant_provider_unref)
VALA_EXTERN GType enchant_pwl_dict_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnchantPwlDict, enchant_provider_dict_unref)
VALA_EXTERN EnchantPwlDict* enchant_pwl_dict_new (void);
VALA_EXTERN EnchantPwlDict* enchant_pwl_dict_construct (GType object_type);
VALA_EXTERN EnchantProviderDict* enchant_provider_dict_new (EnchantProvider* provider,
                                                const gchar* tag);
VALA_EXTERN EnchantProviderDict* enchant_provider_dict_construct (GType object_type,
                                                      EnchantProvider* provider,
                                                      const gchar* tag);
static gint _check_impl_dict_check (EnchantProviderDict* me,
                             const gchar* word,
                             size_t len);
static gchar** _suggest_impl_dict_suggest (EnchantProviderDict* me,
                                    const gchar* word,
                                    size_t len,
                                    size_t* result_length1);
static GType enchant_pwl_dict_get_type_once (void);

void
lock_file (FILE* f)
{
#line 43 "pwl.vala"
	g_return_if_fail (f != NULL);
#line 309 "pwl.c"
}

void
unlock_file (FILE* f)
{
#line 47 "pwl.vala"
	g_return_if_fail (f != NULL);
#line 318 "pwl.c"
}

static gunichar
string_get_char (const gchar* self,
                 glong index)
{
	gunichar result;
#line 1313 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0U);
#line 1314 "glib-2.0.vapi"
	result = g_utf8_get_char (((gchar*) self) + index);
#line 1314 "glib-2.0.vapi"
	return result;
#line 335 "pwl.c"
}

static gchar*
g_unichar_to_string (gunichar self)
{
	gchar* str = NULL;
	gchar* _tmp0_;
	gchar* result;
#line 1122 "glib-2.0.vapi"
	_tmp0_ = g_new0 (gchar, 7);
#line 1122 "glib-2.0.vapi"
	str = (gchar*) _tmp0_;
#line 1123 "glib-2.0.vapi"
	g_unichar_to_utf8 (self, str);
#line 1124 "glib-2.0.vapi"
	result = str;
#line 1124 "glib-2.0.vapi"
	return result;
#line 354 "pwl.c"
}

gchar*
utf8_strtitle (const gchar* str)
{
	gchar* upper_str = NULL;
	gchar* _tmp0_;
	gchar* lower_tail = NULL;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gunichar title_case_char = 0U;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* result;
#line 51 "pwl.vala"
	g_return_val_if_fail (str != NULL, NULL);
#line 52 "pwl.vala"
	_tmp0_ = g_utf8_strup (str, (gssize) -1);
#line 52 "pwl.vala"
	upper_str = _tmp0_;
#line 53 "pwl.vala"
	_tmp1_ = g_utf8_next_char (upper_str);
#line 53 "pwl.vala"
	_tmp2_ = g_utf8_strdown (_tmp1_, (gssize) -1);
#line 53 "pwl.vala"
	lower_tail = _tmp2_;
#line 54 "pwl.vala"
	title_case_char = g_unichar_totitle (string_get_char (upper_str, (glong) 0));
#line 55 "pwl.vala"
	_tmp3_ = g_unichar_to_string (title_case_char);
#line 55 "pwl.vala"
	_tmp4_ = _tmp3_;
#line 55 "pwl.vala"
	_tmp5_ = g_strdup_printf ("%s%s", _tmp4_, lower_tail);
#line 55 "pwl.vala"
	_tmp6_ = _tmp5_;
#line 55 "pwl.vala"
	_g_free0 (_tmp4_);
#line 55 "pwl.vala"
	result = _tmp6_;
#line 55 "pwl.vala"
	_g_free0 (lower_tail);
#line 55 "pwl.vala"
	_g_free0 (upper_str);
#line 55 "pwl.vala"
	return result;
#line 403 "pwl.c"
}

static gboolean
string_get_next_char (const gchar* self,
                      gint* index,
                      gunichar* c)
{
	gunichar _vala_c = 0U;
	gboolean result;
#line 1302 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1303 "glib-2.0.vapi"
	_vala_c = g_utf8_get_char (((gchar*) self) + (*index));
#line 1304 "glib-2.0.vapi"
	if (_vala_c != ((gunichar) 0)) {
#line 419 "pwl.c"
		gchar* _tmp0_;
#line 1305 "glib-2.0.vapi"
		_tmp0_ = g_utf8_next_char (((gchar*) self) + (*index));
#line 1305 "glib-2.0.vapi"
		*index = (gint) (_tmp0_ - ((gchar*) self));
#line 1306 "glib-2.0.vapi"
		result = TRUE;
#line 1306 "glib-2.0.vapi"
		if (c) {
#line 1306 "glib-2.0.vapi"
			*c = _vala_c;
#line 431 "pwl.c"
		}
#line 1306 "glib-2.0.vapi"
		return result;
#line 435 "pwl.c"
	} else {
#line 1308 "glib-2.0.vapi"
		result = FALSE;
#line 1308 "glib-2.0.vapi"
		if (c) {
#line 1308 "glib-2.0.vapi"
			*c = _vala_c;
#line 443 "pwl.c"
		}
#line 1308 "glib-2.0.vapi"
		return result;
#line 447 "pwl.c"
	}
}

gboolean
is_all_caps (const gchar* word)
{
	gboolean has_cap = FALSE;
	gunichar c = 0U;
	gboolean result;
#line 58 "pwl.vala"
	g_return_val_if_fail (word != NULL, FALSE);
#line 59 "pwl.vala"
	has_cap = FALSE;
#line 461 "pwl.c"
	{
		gint i = 0;
#line 61 "pwl.vala"
		i = 0;
#line 466 "pwl.c"
		{
			gboolean _tmp0_ = FALSE;
#line 61 "pwl.vala"
			_tmp0_ = TRUE;
#line 61 "pwl.vala"
			while (TRUE) {
#line 473 "pwl.c"
				gunichar _tmp1_ = 0U;
				gboolean _tmp2_;
				GUnicodeType type = 0;
#line 61 "pwl.vala"
				if (!_tmp0_) {
#line 479 "pwl.c"
				}
#line 61 "pwl.vala"
				_tmp0_ = FALSE;
#line 61 "pwl.vala"
				_tmp2_ = string_get_next_char (word, &i, &_tmp1_);
#line 61 "pwl.vala"
				c = _tmp1_;
#line 61 "pwl.vala"
				if (!_tmp2_) {
#line 61 "pwl.vala"
					break;
#line 491 "pwl.c"
				}
#line 62 "pwl.vala"
				type = g_unichar_type (c);
#line 63 "pwl.vala"
				switch (type) {
#line 63 "pwl.vala"
					case G_UNICODE_UPPERCASE_LETTER:
#line 499 "pwl.c"
					{
#line 65 "pwl.vala"
						has_cap = TRUE;
#line 66 "pwl.vala"
						break;
#line 505 "pwl.c"
					}
#line 63 "pwl.vala"
					case G_UNICODE_TITLECASE_LETTER:
#line 63 "pwl.vala"
					case G_UNICODE_LOWERCASE_LETTER:
#line 511 "pwl.c"
					{
#line 69 "pwl.vala"
						result = FALSE;
#line 69 "pwl.vala"
						return result;
#line 517 "pwl.c"
					}
					default:
#line 63 "pwl.vala"
					case G_UNICODE_CONTROL:
#line 63 "pwl.vala"
					case G_UNICODE_FORMAT:
#line 63 "pwl.vala"
					case G_UNICODE_UNASSIGNED:
#line 63 "pwl.vala"
					case G_UNICODE_PRIVATE_USE:
#line 63 "pwl.vala"
					case G_UNICODE_SURROGATE:
#line 63 "pwl.vala"
					case G_UNICODE_MODIFIER_LETTER:
#line 63 "pwl.vala"
					case G_UNICODE_OTHER_LETTER:
#line 63 "pwl.vala"
					case G_UNICODE_SPACING_MARK:
#line 63 "pwl.vala"
					case G_UNICODE_ENCLOSING_MARK:
#line 63 "pwl.vala"
					case G_UNICODE_NON_SPACING_MARK:
#line 63 "pwl.vala"
					case G_UNICODE_DECIMAL_NUMBER:
#line 63 "pwl.vala"
					case G_UNICODE_LETTER_NUMBER:
#line 63 "pwl.vala"
					case G_UNICODE_OTHER_NUMBER:
#line 63 "pwl.vala"
					case G_UNICODE_CONNECT_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_DASH_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_CLOSE_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_FINAL_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_INITIAL_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_OTHER_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_OPEN_PUNCTUATION:
#line 63 "pwl.vala"
					case G_UNICODE_CURRENCY_SYMBOL:
#line 63 "pwl.vala"
					case G_UNICODE_MODIFIER_SYMBOL:
#line 63 "pwl.vala"
					case G_UNICODE_MATH_SYMBOL:
#line 63 "pwl.vala"
					case G_UNICODE_OTHER_SYMBOL:
#line 63 "pwl.vala"
					case G_UNICODE_LINE_SEPARATOR:
#line 63 "pwl.vala"
					case G_UNICODE_PARAGRAPH_SEPARATOR:
#line 63 "pwl.vala"
					case G_UNICODE_SPACE_SEPARATOR:
#line 574 "pwl.c"
					{
#line 99 "pwl.vala"
						break;
#line 578 "pwl.c"
					}
				}
			}
		}
	}
#line 103 "pwl.vala"
	result = has_cap;
#line 103 "pwl.vala"
	return result;
#line 588 "pwl.c"
}

gboolean
is_title_case (const gchar* word)
{
	gint i = 0;
	gunichar c = 0U;
	gunichar _tmp0_ = 0U;
	GUnicodeType type = 0;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean result;
#line 106 "pwl.vala"
	g_return_val_if_fail (word != NULL, FALSE);
#line 107 "pwl.vala"
	i = 0;
#line 109 "pwl.vala"
	string_get_next_char (word, &i, &_tmp0_);
#line 109 "pwl.vala"
	c = _tmp0_;
#line 110 "pwl.vala"
	type = g_unichar_type (c);
#line 111 "pwl.vala"
	if (type != G_UNICODE_UPPERCASE_LETTER) {
#line 111 "pwl.vala"
		_tmp2_ = type != G_UNICODE_TITLECASE_LETTER;
#line 615 "pwl.c"
	} else {
#line 111 "pwl.vala"
		_tmp2_ = FALSE;
#line 619 "pwl.c"
	}
#line 111 "pwl.vala"
	if (_tmp2_) {
#line 111 "pwl.vala"
		_tmp1_ = TRUE;
#line 625 "pwl.c"
	} else {
#line 112 "pwl.vala"
		_tmp1_ = c != g_unichar_totitle (c);
#line 629 "pwl.c"
	}
#line 111 "pwl.vala"
	if (_tmp1_) {
#line 113 "pwl.vala"
		result = FALSE;
#line 113 "pwl.vala"
		return result;
#line 637 "pwl.c"
	}
#line 115 "pwl.vala"
	while (TRUE) {
#line 641 "pwl.c"
		gunichar _tmp3_ = 0U;
		gboolean _tmp4_;
		gboolean _tmp5_ = FALSE;
#line 115 "pwl.vala"
		_tmp4_ = string_get_next_char (word, &i, &_tmp3_);
#line 115 "pwl.vala"
		c = _tmp3_;
#line 115 "pwl.vala"
		if (!_tmp4_) {
#line 115 "pwl.vala"
			break;
#line 653 "pwl.c"
		}
#line 116 "pwl.vala"
		type = g_unichar_type (c);
#line 117 "pwl.vala"
		if (type == G_UNICODE_UPPERCASE_LETTER) {
#line 117 "pwl.vala"
			_tmp5_ = TRUE;
#line 661 "pwl.c"
		} else {
#line 117 "pwl.vala"
			_tmp5_ = type == G_UNICODE_TITLECASE_LETTER;
#line 665 "pwl.c"
		}
#line 117 "pwl.vala"
		if (_tmp5_) {
#line 118 "pwl.vala"
			result = FALSE;
#line 118 "pwl.vala"
			return result;
#line 673 "pwl.c"
		}
	}
#line 121 "pwl.vala"
	result = TRUE;
#line 121 "pwl.vala"
	return result;
#line 680 "pwl.c"
}

static inline gpointer
enchant_pwl_get_instance_private (EnchantPWL* self)
{
	return G_STRUCT_MEMBER_P (self, EnchantPWL_private_offset);
}

static void
_g_free0_ (gpointer var)
{
#line 128 "pwl.vala"
	var = (g_free (var), NULL);
#line 694 "pwl.c"
}

EnchantPWL*
enchant_pwl_construct (GType object_type,
                       const gchar* filename,
                       gboolean exclude)
{
	EnchantPWL* self = NULL;
	gchar* _tmp0_;
#line 130 "pwl.vala"
	self = (EnchantPWL*) g_type_create_instance (object_type);
#line 131 "pwl.vala"
	_tmp0_ = g_strdup (filename);
#line 131 "pwl.vala"
	_g_free0 (self->priv->filename);
#line 131 "pwl.vala"
	self->priv->filename = _tmp0_;
#line 132 "pwl.vala"
	self->priv->exclude = exclude;
#line 130 "pwl.vala"
	return self;
#line 716 "pwl.c"
}

EnchantPWL*
enchant_pwl_new (const gchar* filename,
                 gboolean exclude)
{
#line 130 "pwl.vala"
	return enchant_pwl_construct (TYPE_ENCHANT_PWL, filename, exclude);
#line 725 "pwl.c"
}

static void
enchant_pwl_add_to_table (EnchantPWL* self,
                          const gchar* word)
{
	gchar* normalized_word = NULL;
	gchar* _tmp0_;
	GHashTable* _tmp1_;
	const gchar* _tmp2_;
#line 135 "pwl.vala"
	g_return_if_fail (self != NULL);
#line 135 "pwl.vala"
	g_return_if_fail (word != NULL);
#line 136 "pwl.vala"
	_tmp0_ = g_utf8_normalize (word, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 136 "pwl.vala"
	normalized_word = _tmp0_;
#line 137 "pwl.vala"
	_tmp1_ = self->priv->words;
#line 137 "pwl.vala"
	_tmp2_ = normalized_word;
#line 137 "pwl.vala"
	if (!g_hash_table_contains (_tmp1_, _tmp2_)) {
#line 750 "pwl.c"
		GHashTable* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 138 "pwl.vala"
		_tmp3_ = self->priv->words;
#line 138 "pwl.vala"
		_tmp4_ = normalized_word;
#line 138 "pwl.vala"
		_tmp5_ = g_strdup (_tmp4_);
#line 138 "pwl.vala"
		_tmp6_ = g_strdup (word);
#line 138 "pwl.vala"
		g_hash_table_insert (_tmp3_, _tmp5_, _tmp6_);
#line 765 "pwl.c"
	}
#line 135 "pwl.vala"
	_g_free0 (normalized_word);
#line 769 "pwl.c"
}

void
enchant_pwl_add (EnchantPWL* self,
                 EnchantDict* session,
                 const gchar* word_buf,
                 ssize_t len)
{
	gchar* word = NULL;
	gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
#line 141 "pwl.vala"
	g_return_if_fail (self != NULL);
#line 141 "pwl.vala"
	g_return_if_fail (session != NULL);
#line 142 "pwl.vala"
	if (word_buf == NULL) {
#line 143 "pwl.vala"
		return;
#line 792 "pwl.c"
	}
#line 145 "pwl.vala"
	_tmp0_ = buf_to_utf8_string (word_buf, (gssize) len);
#line 145 "pwl.vala"
	word = _tmp0_;
#line 146 "pwl.vala"
	_tmp2_ = word;
#line 146 "pwl.vala"
	if (_tmp2_ == NULL) {
#line 146 "pwl.vala"
		_tmp1_ = TRUE;
#line 804 "pwl.c"
	} else {
		const gchar* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
#line 146 "pwl.vala"
		_tmp3_ = word;
#line 146 "pwl.vala"
		_tmp4_ = strlen (_tmp3_);
#line 146 "pwl.vala"
		_tmp5_ = _tmp4_;
#line 146 "pwl.vala"
		_tmp1_ = _tmp5_ == 0;
#line 817 "pwl.c"
	}
#line 146 "pwl.vala"
	if (_tmp1_) {
#line 147 "pwl.vala"
		_g_free0 (word);
#line 147 "pwl.vala"
		return;
#line 825 "pwl.c"
	}
#line 149 "pwl.vala"
	enchant_pwl_refresh_from_file (self, session);
#line 150 "pwl.vala"
	_tmp6_ = word;
#line 150 "pwl.vala"
	enchant_pwl_add_to_table (self, _tmp6_);
#line 152 "pwl.vala"
	_tmp7_ = self->priv->filename;
#line 152 "pwl.vala"
	if (_tmp7_ != NULL) {
#line 837 "pwl.c"
		FILE* f = NULL;
		const gchar* _tmp8_;
		FILE* _tmp9_;
		FILE* _tmp10_;
#line 153 "pwl.vala"
		_tmp8_ = self->priv->filename;
#line 153 "pwl.vala"
		_tmp9_ = g_fopen (_tmp8_, "a+");
#line 153 "pwl.vala"
		f = _tmp9_;
#line 154 "pwl.vala"
		_tmp10_ = f;
#line 154 "pwl.vala"
		if (_tmp10_ != NULL) {
#line 852 "pwl.c"
			FILE* _tmp11_;
			struct stat stats = {0};
			const gchar* _tmp12_;
			struct stat _tmp13_ = {0};
			gint _tmp14_;
			FILE* _tmp16_;
			FILE* _tmp20_;
			const gchar* _tmp21_;
			FILE* _tmp23_;
#line 157 "pwl.vala"
			_tmp11_ = f;
#line 157 "pwl.vala"
			lock_file (_tmp11_);
#line 159 "pwl.vala"
			_tmp12_ = self->priv->filename;
#line 159 "pwl.vala"
			_tmp14_ = stat (_tmp12_, &_tmp13_);
#line 159 "pwl.vala"
			stats = _tmp13_;
#line 159 "pwl.vala"
			if (_tmp14_ == 0) {
#line 874 "pwl.c"
				struct stat _tmp15_;
#line 160 "pwl.vala"
				_tmp15_ = stats;
#line 160 "pwl.vala"
				self->priv->file_changed = _tmp15_.st_mtime;
#line 880 "pwl.c"
			}
#line 163 "pwl.vala"
			_tmp16_ = f;
#line 163 "pwl.vala"
			if (fseek (_tmp16_, (glong) -1, SEEK_END) == 0) {
#line 886 "pwl.c"
				gint c = 0;
				FILE* _tmp17_;
				FILE* _tmp18_;
#line 164 "pwl.vala"
				_tmp17_ = f;
#line 164 "pwl.vala"
				c = fgetc (_tmp17_);
#line 165 "pwl.vala"
				_tmp18_ = f;
#line 165 "pwl.vala"
				fseek (_tmp18_, (glong) 0, SEEK_CUR);
#line 166 "pwl.vala"
				if (c != ((gint) '\n')) {
#line 900 "pwl.c"
					FILE* _tmp19_;
#line 167 "pwl.vala"
					_tmp19_ = f;
#line 167 "pwl.vala"
					fputc ('\n', _tmp19_);
#line 906 "pwl.c"
				}
			}
#line 170 "pwl.vala"
			_tmp20_ = f;
#line 170 "pwl.vala"
			_tmp21_ = word;
#line 170 "pwl.vala"
			if (fputs (_tmp21_, _tmp20_) != EOF) {
#line 915 "pwl.c"
				FILE* _tmp22_;
#line 171 "pwl.vala"
				_tmp22_ = f;
#line 171 "pwl.vala"
				fputc ('\n', _tmp22_);
#line 921 "pwl.c"
			}
#line 172 "pwl.vala"
			_tmp23_ = f;
#line 172 "pwl.vala"
			unlock_file (_tmp23_);
#line 927 "pwl.c"
		}
#line 152 "pwl.vala"
		_fclose0 (f);
#line 931 "pwl.c"
	}
#line 141 "pwl.vala"
	_g_free0 (word);
#line 935 "pwl.c"
}

static gint
string_index_of (const gchar* self,
                 const gchar* needle,
                 gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result;
#line 1184 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, -1);
#line 1184 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, -1);
#line 1185 "glib-2.0.vapi"
	_tmp0_ = strstr (((gchar*) self) + start_index, (gchar*) needle);
#line 1185 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1187 "glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1187 "glib-2.0.vapi"
	if (_tmp1_ != NULL) {
#line 959 "pwl.c"
		gchar* _tmp2_;
#line 1188 "glib-2.0.vapi"
		_tmp2_ = _result_;
#line 1188 "glib-2.0.vapi"
		result = (gint) (_tmp2_ - ((gchar*) self));
#line 1188 "glib-2.0.vapi"
		return result;
#line 967 "pwl.c"
	} else {
#line 1190 "glib-2.0.vapi"
		result = -1;
#line 1190 "glib-2.0.vapi"
		return result;
#line 973 "pwl.c"
	}
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1503 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1503 "glib-2.0.vapi"
	end = _tmp0_;
#line 1504 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1504 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1505 "glib-2.0.vapi"
		result = maxlen;
#line 1505 "glib-2.0.vapi"
		return result;
#line 997 "pwl.c"
	} else {
		gchar* _tmp2_;
#line 1507 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1507 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1507 "glib-2.0.vapi"
		return result;
#line 1006 "pwl.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1514 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1516 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1516 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 1025 "pwl.c"
	} else {
#line 1516 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 1029 "pwl.c"
	}
#line 1516 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1518 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 1035 "pwl.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1520 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1520 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1520 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 1045 "pwl.c"
	}
#line 1523 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1524 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1525 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 1053 "pwl.c"
	} else {
#line 1527 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 1057 "pwl.c"
	}
#line 1529 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1530 "glib-2.0.vapi"
		len = string_length - offset;
#line 1063 "pwl.c"
	}
#line 1532 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1533 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1533 "glib-2.0.vapi"
	result = _tmp3_;
#line 1533 "glib-2.0.vapi"
	return result;
#line 1073 "pwl.c"
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1283 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1284 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1284 "glib-2.0.vapi"
	result = _tmp0_;
#line 1284 "glib-2.0.vapi"
	return result;
#line 1090 "pwl.c"
}

void
enchant_pwl_remove (EnchantPWL* self,
                    EnchantDict* session,
                    const gchar* word_buf,
                    ssize_t len)
{
	gchar* word = NULL;
	gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	GHashTable* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	GError* _inner_error0_ = NULL;
#line 177 "pwl.vala"
	g_return_if_fail (self != NULL);
#line 177 "pwl.vala"
	g_return_if_fail (session != NULL);
#line 177 "pwl.vala"
	g_return_if_fail (word_buf != NULL);
#line 178 "pwl.vala"
	if (word_buf == NULL) {
#line 179 "pwl.vala"
		return;
#line 1119 "pwl.c"
	}
#line 181 "pwl.vala"
	_tmp0_ = buf_to_utf8_string (word_buf, (gssize) len);
#line 181 "pwl.vala"
	word = _tmp0_;
#line 182 "pwl.vala"
	_tmp2_ = word;
#line 182 "pwl.vala"
	if (_tmp2_ == NULL) {
#line 182 "pwl.vala"
		_tmp1_ = TRUE;
#line 1131 "pwl.c"
	} else {
		const gchar* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
#line 182 "pwl.vala"
		_tmp3_ = word;
#line 182 "pwl.vala"
		_tmp4_ = strlen (_tmp3_);
#line 182 "pwl.vala"
		_tmp5_ = _tmp4_;
#line 182 "pwl.vala"
		_tmp1_ = _tmp5_ == 0;
#line 1144 "pwl.c"
	}
#line 182 "pwl.vala"
	if (_tmp1_) {
#line 183 "pwl.vala"
		_g_free0 (word);
#line 183 "pwl.vala"
		return;
#line 1152 "pwl.c"
	}
#line 185 "pwl.vala"
	enchant_pwl_refresh_from_file (self, session);
#line 186 "pwl.vala"
	_tmp6_ = self->priv->words;
#line 186 "pwl.vala"
	_tmp7_ = word;
#line 186 "pwl.vala"
	_tmp8_ = g_utf8_normalize (_tmp7_, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 186 "pwl.vala"
	_tmp9_ = _tmp8_;
#line 186 "pwl.vala"
	g_hash_table_remove (_tmp6_, _tmp9_);
#line 186 "pwl.vala"
	_g_free0 (_tmp9_);
#line 188 "pwl.vala"
	_tmp10_ = self->priv->filename;
#line 188 "pwl.vala"
	if (_tmp10_ != NULL) {
#line 1172 "pwl.c"
		gchar* contents = NULL;
		gsize length = 0UL;
		FILE* f = NULL;
		const gchar* _tmp14_;
		FILE* _tmp15_;
		FILE* _tmp16_;
		{
			const gchar* _tmp11_;
			gchar* _tmp12_ = NULL;
			gsize _tmp13_ = 0UL;
#line 192 "pwl.vala"
			_tmp11_ = self->priv->filename;
#line 192 "pwl.vala"
			g_file_get_contents (_tmp11_, &_tmp12_, &_tmp13_, &_inner_error0_);
#line 192 "pwl.vala"
			_g_free0 (contents);
#line 192 "pwl.vala"
			contents = _tmp12_;
#line 192 "pwl.vala"
			length = _tmp13_;
#line 192 "pwl.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 192 "pwl.vala"
				if (_inner_error0_->domain == G_FILE_ERROR) {
#line 1197 "pwl.c"
					goto __catch0_g_file_error;
				}
#line 192 "pwl.vala"
				_g_free0 (contents);
#line 192 "pwl.vala"
				_g_free0 (word);
#line 192 "pwl.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 192 "pwl.vala"
				g_clear_error (&_inner_error0_);
#line 192 "pwl.vala"
				return;
#line 1210 "pwl.c"
			}
		}
		goto __finally0;
		__catch0_g_file_error:
		{
#line 191 "pwl.vala"
			g_clear_error (&_inner_error0_);
#line 194 "pwl.vala"
			_g_free0 (contents);
#line 194 "pwl.vala"
			_g_free0 (word);
#line 194 "pwl.vala"
			return;
#line 1224 "pwl.c"
		}
		__finally0:
#line 191 "pwl.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 191 "pwl.vala"
			_g_free0 (contents);
#line 191 "pwl.vala"
			_g_free0 (word);
#line 191 "pwl.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 191 "pwl.vala"
			g_clear_error (&_inner_error0_);
#line 191 "pwl.vala"
			return;
#line 1239 "pwl.c"
		}
#line 197 "pwl.vala"
		_tmp14_ = self->priv->filename;
#line 197 "pwl.vala"
		_tmp15_ = g_fopen (_tmp14_, "wb");
#line 197 "pwl.vala"
		f = _tmp15_;
#line 198 "pwl.vala"
		_tmp16_ = f;
#line 198 "pwl.vala"
		if (_tmp16_ != NULL) {
#line 1251 "pwl.c"
			FILE* _tmp17_;
			glong filestart = 0L;
			const gchar* _tmp18_;
			struct stat stats = {0};
			const gchar* _tmp68_;
			struct stat _tmp69_ = {0};
			gint _tmp70_;
			FILE* _tmp72_;
#line 199 "pwl.vala"
			_tmp17_ = f;
#line 199 "pwl.vala"
			lock_file (_tmp17_);
#line 200 "pwl.vala"
			filestart = (glong) 0;
#line 203 "pwl.vala"
			_tmp18_ = contents;
#line 203 "pwl.vala"
			if (BOM == string_get_char (_tmp18_, filestart)) {
#line 1270 "pwl.c"
				const gchar* _tmp19_;
				const gchar* _tmp20_;
				gchar* _tmp21_;
				FILE* _tmp22_;
				gchar* _tmp23_;
				gchar* _tmp24_;
#line 204 "pwl.vala"
				_tmp19_ = contents;
#line 204 "pwl.vala"
				_tmp20_ = g_utf8_next_char (_tmp19_);
#line 204 "pwl.vala"
				_tmp21_ = g_strdup (_tmp20_);
#line 204 "pwl.vala"
				_g_free0 (contents);
#line 204 "pwl.vala"
				contents = _tmp21_;
#line 205 "pwl.vala"
				_tmp22_ = f;
#line 205 "pwl.vala"
				_tmp23_ = g_unichar_to_string (BOM);
#line 205 "pwl.vala"
				_tmp24_ = _tmp23_;
#line 205 "pwl.vala"
				fputs (_tmp24_, _tmp22_);
#line 205 "pwl.vala"
				_g_free0 (_tmp24_);
#line 1297 "pwl.c"
			}
			{
				gint start_index = 0;
#line 208 "pwl.vala"
				start_index = 0;
#line 1303 "pwl.c"
				{
					gboolean _tmp25_ = FALSE;
#line 208 "pwl.vala"
					_tmp25_ = TRUE;
#line 208 "pwl.vala"
					while (TRUE) {
#line 1310 "pwl.c"
						gint word_pos = 0;
						const gchar* _tmp26_;
						const gchar* _tmp27_;
#line 208 "pwl.vala"
						if (!_tmp25_) {
#line 1316 "pwl.c"
						}
#line 208 "pwl.vala"
						_tmp25_ = FALSE;
#line 210 "pwl.vala"
						_tmp26_ = contents;
#line 210 "pwl.vala"
						_tmp27_ = word;
#line 210 "pwl.vala"
						word_pos = string_index_of (_tmp26_, _tmp27_, start_index);
#line 211 "pwl.vala"
						if (word_pos == -1) {
#line 1328 "pwl.c"
							FILE* _tmp28_;
							const gchar* _tmp29_;
							gchar* _tmp30_;
							gchar* _tmp31_;
#line 212 "pwl.vala"
							_tmp28_ = f;
#line 212 "pwl.vala"
							_tmp29_ = contents;
#line 212 "pwl.vala"
							_tmp30_ = string_substring (_tmp29_, (glong) start_index, (glong) -1);
#line 212 "pwl.vala"
							_tmp31_ = _tmp30_;
#line 212 "pwl.vala"
							fputs (_tmp31_, _tmp28_);
#line 212 "pwl.vala"
							_g_free0 (_tmp31_);
#line 213 "pwl.vala"
							break;
#line 1347 "pwl.c"
						} else {
							gboolean _tmp32_ = FALSE;
							gboolean _tmp33_ = FALSE;
							gboolean _tmp34_ = FALSE;
#line 215 "pwl.vala"
							if (word_pos == 0) {
#line 215 "pwl.vala"
								_tmp34_ = TRUE;
#line 1356 "pwl.c"
							} else {
								const gchar* _tmp35_;
#line 215 "pwl.vala"
								_tmp35_ = contents;
#line 215 "pwl.vala"
								_tmp34_ = string_get (_tmp35_, (glong) (word_pos - 1)) == '\n';
#line 1363 "pwl.c"
							}
#line 215 "pwl.vala"
							if (_tmp34_) {
#line 215 "pwl.vala"
								_tmp33_ = TRUE;
#line 1369 "pwl.c"
							} else {
								const gchar* _tmp36_;
#line 215 "pwl.vala"
								_tmp36_ = contents;
#line 215 "pwl.vala"
								_tmp33_ = string_get (_tmp36_, (glong) (word_pos - 1)) == '\r';
#line 1376 "pwl.c"
							}
#line 215 "pwl.vala"
							if (_tmp33_) {
#line 1380 "pwl.c"
								gboolean _tmp37_ = FALSE;
								gboolean _tmp38_ = FALSE;
								const gchar* _tmp39_;
								gint _tmp40_;
								gint _tmp41_;
								const gchar* _tmp42_;
								gint _tmp43_;
								gint _tmp44_;
#line 216 "pwl.vala"
								_tmp39_ = word;
#line 216 "pwl.vala"
								_tmp40_ = strlen (_tmp39_);
#line 216 "pwl.vala"
								_tmp41_ = _tmp40_;
#line 216 "pwl.vala"
								_tmp42_ = contents;
#line 216 "pwl.vala"
								_tmp43_ = strlen (_tmp42_);
#line 216 "pwl.vala"
								_tmp44_ = _tmp43_;
#line 216 "pwl.vala"
								if ((word_pos + _tmp41_) == _tmp44_) {
#line 216 "pwl.vala"
									_tmp38_ = TRUE;
#line 1405 "pwl.c"
								} else {
									const gchar* _tmp45_;
									const gchar* _tmp46_;
									gint _tmp47_;
									gint _tmp48_;
#line 216 "pwl.vala"
									_tmp45_ = contents;
#line 216 "pwl.vala"
									_tmp46_ = word;
#line 216 "pwl.vala"
									_tmp47_ = strlen (_tmp46_);
#line 216 "pwl.vala"
									_tmp48_ = _tmp47_;
#line 216 "pwl.vala"
									_tmp38_ = string_get (_tmp45_, (glong) (word_pos + _tmp48_)) == '\n';
#line 1421 "pwl.c"
								}
#line 216 "pwl.vala"
								if (_tmp38_) {
#line 216 "pwl.vala"
									_tmp37_ = TRUE;
#line 1427 "pwl.c"
								} else {
									const gchar* _tmp49_;
									const gchar* _tmp50_;
									gint _tmp51_;
									gint _tmp52_;
#line 216 "pwl.vala"
									_tmp49_ = contents;
#line 216 "pwl.vala"
									_tmp50_ = word;
#line 216 "pwl.vala"
									_tmp51_ = strlen (_tmp50_);
#line 216 "pwl.vala"
									_tmp52_ = _tmp51_;
#line 216 "pwl.vala"
									_tmp37_ = string_get (_tmp49_, (glong) (word_pos + _tmp52_)) == '\r';
#line 1443 "pwl.c"
								}
#line 216 "pwl.vala"
								_tmp32_ = _tmp37_;
#line 1447 "pwl.c"
							} else {
#line 215 "pwl.vala"
								_tmp32_ = FALSE;
#line 1451 "pwl.c"
							}
#line 215 "pwl.vala"
							if (_tmp32_) {
#line 1455 "pwl.c"
								FILE* _tmp53_;
								const gchar* _tmp54_;
								gchar* _tmp55_;
								gchar* _tmp56_;
								const gchar* _tmp57_;
								gint _tmp58_;
								gint _tmp59_;
#line 217 "pwl.vala"
								_tmp53_ = f;
#line 217 "pwl.vala"
								_tmp54_ = contents;
#line 217 "pwl.vala"
								_tmp55_ = string_substring (_tmp54_, (glong) start_index, (glong) (word_pos - start_index));
#line 217 "pwl.vala"
								_tmp56_ = _tmp55_;
#line 217 "pwl.vala"
								fputs (_tmp56_, _tmp53_);
#line 217 "pwl.vala"
								_g_free0 (_tmp56_);
#line 218 "pwl.vala"
								_tmp57_ = word;
#line 218 "pwl.vala"
								_tmp58_ = strlen (_tmp57_);
#line 218 "pwl.vala"
								_tmp59_ = _tmp58_;
#line 218 "pwl.vala"
								start_index = word_pos + _tmp59_;
#line 219 "pwl.vala"
								while (TRUE) {
#line 1485 "pwl.c"
									gboolean _tmp60_ = FALSE;
									const gchar* _tmp61_;
									gint _tmp63_;
#line 219 "pwl.vala"
									_tmp61_ = contents;
#line 219 "pwl.vala"
									if (string_get (_tmp61_, (glong) start_index) == '\n') {
#line 219 "pwl.vala"
										_tmp60_ = TRUE;
#line 1495 "pwl.c"
									} else {
										const gchar* _tmp62_;
#line 219 "pwl.vala"
										_tmp62_ = contents;
#line 219 "pwl.vala"
										_tmp60_ = string_get (_tmp62_, (glong) start_index) == '\r';
#line 1502 "pwl.c"
									}
#line 219 "pwl.vala"
									if (!_tmp60_) {
#line 219 "pwl.vala"
										break;
#line 1508 "pwl.c"
									}
#line 220 "pwl.vala"
									start_index = start_index + 1;
#line 220 "pwl.vala"
									_tmp63_ = start_index;
#line 1514 "pwl.c"
								}
							} else {
								FILE* _tmp64_;
								const gchar* _tmp65_;
								gchar* _tmp66_;
								gchar* _tmp67_;
#line 222 "pwl.vala"
								_tmp64_ = f;
#line 222 "pwl.vala"
								_tmp65_ = contents;
#line 222 "pwl.vala"
								_tmp66_ = string_substring (_tmp65_, (glong) start_index, (glong) ((word_pos - start_index) + 1));
#line 222 "pwl.vala"
								_tmp67_ = _tmp66_;
#line 222 "pwl.vala"
								fputs (_tmp67_, _tmp64_);
#line 222 "pwl.vala"
								_g_free0 (_tmp67_);
#line 223 "pwl.vala"
								start_index = word_pos + 1;
#line 1535 "pwl.c"
							}
						}
					}
				}
			}
#line 229 "pwl.vala"
			_tmp68_ = self->priv->filename;
#line 229 "pwl.vala"
			_tmp70_ = stat (_tmp68_, &_tmp69_);
#line 229 "pwl.vala"
			stats = _tmp69_;
#line 229 "pwl.vala"
			if (_tmp70_ == 0) {
#line 1549 "pwl.c"
				struct stat _tmp71_;
#line 230 "pwl.vala"
				_tmp71_ = stats;
#line 230 "pwl.vala"
				self->priv->file_changed = _tmp71_.st_mtime;
#line 1555 "pwl.c"
			}
#line 232 "pwl.vala"
			_tmp72_ = f;
#line 232 "pwl.vala"
			unlock_file (_tmp72_);
#line 1561 "pwl.c"
		}
#line 188 "pwl.vala"
		_fclose0 (f);
#line 188 "pwl.vala"
		_g_free0 (contents);
#line 1567 "pwl.c"
	}
#line 177 "pwl.vala"
	_g_free0 (word);
#line 1571 "pwl.c"
}

gint
enchant_pwl_check (EnchantPWL* self,
                   EnchantDict* session,
                   const gchar* word_buf,
                   ssize_t len)
{
	gchar* word = NULL;
	gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	GHashTable* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gboolean _tmp10_;
	gboolean all_caps = FALSE;
	gboolean _tmp11_ = FALSE;
	const gchar* _tmp12_;
	gint result;
#line 237 "pwl.vala"
	g_return_val_if_fail (self != NULL, -1);
#line 237 "pwl.vala"
	g_return_val_if_fail (session != NULL, -1);
#line 237 "pwl.vala"
	g_return_val_if_fail (word_buf != NULL, -1);
#line 238 "pwl.vala"
	if (word_buf == NULL) {
#line 239 "pwl.vala"
		result = 0;
#line 239 "pwl.vala"
		return result;
#line 1605 "pwl.c"
	}
#line 241 "pwl.vala"
	_tmp0_ = buf_to_utf8_string (word_buf, (gssize) len);
#line 241 "pwl.vala"
	word = _tmp0_;
#line 242 "pwl.vala"
	_tmp2_ = word;
#line 242 "pwl.vala"
	if (_tmp2_ == NULL) {
#line 242 "pwl.vala"
		_tmp1_ = TRUE;
#line 1617 "pwl.c"
	} else {
		const gchar* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
#line 242 "pwl.vala"
		_tmp3_ = word;
#line 242 "pwl.vala"
		_tmp4_ = strlen (_tmp3_);
#line 242 "pwl.vala"
		_tmp5_ = _tmp4_;
#line 242 "pwl.vala"
		_tmp1_ = _tmp5_ == 0;
#line 1630 "pwl.c"
	}
#line 242 "pwl.vala"
	if (_tmp1_) {
#line 243 "pwl.vala"
		result = 0;
#line 243 "pwl.vala"
		_g_free0 (word);
#line 243 "pwl.vala"
		return result;
#line 1640 "pwl.c"
	}
#line 245 "pwl.vala"
	enchant_pwl_refresh_from_file (self, session);
#line 247 "pwl.vala"
	_tmp6_ = self->priv->words;
#line 247 "pwl.vala"
	_tmp7_ = word;
#line 247 "pwl.vala"
	_tmp8_ = g_utf8_normalize (_tmp7_, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 247 "pwl.vala"
	_tmp9_ = _tmp8_;
#line 247 "pwl.vala"
	_tmp10_ = g_hash_table_contains (_tmp6_, _tmp9_);
#line 247 "pwl.vala"
	_g_free0 (_tmp9_);
#line 247 "pwl.vala"
	if (_tmp10_) {
#line 248 "pwl.vala"
		result = 0;
#line 248 "pwl.vala"
		_g_free0 (word);
#line 248 "pwl.vala"
		return result;
#line 1664 "pwl.c"
	}
#line 250 "pwl.vala"
	all_caps = FALSE;
#line 251 "pwl.vala"
	_tmp12_ = word;
#line 251 "pwl.vala"
	if (is_title_case (_tmp12_)) {
#line 251 "pwl.vala"
		_tmp11_ = TRUE;
#line 1674 "pwl.c"
	} else {
		const gchar* _tmp13_;
#line 251 "pwl.vala"
		_tmp13_ = word;
#line 251 "pwl.vala"
		all_caps = is_all_caps (_tmp13_);
#line 251 "pwl.vala"
		_tmp11_ = all_caps;
#line 1683 "pwl.c"
	}
#line 251 "pwl.vala"
	if (_tmp11_) {
#line 1687 "pwl.c"
		gchar* lower_case_word = NULL;
		const gchar* _tmp14_;
		gchar* _tmp15_;
		GHashTable* _tmp16_;
		const gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		gboolean _tmp20_;
#line 252 "pwl.vala"
		_tmp14_ = word;
#line 252 "pwl.vala"
		_tmp15_ = g_utf8_strdown (_tmp14_, (gssize) -1);
#line 252 "pwl.vala"
		lower_case_word = _tmp15_;
#line 253 "pwl.vala"
		_tmp16_ = self->priv->words;
#line 253 "pwl.vala"
		_tmp17_ = lower_case_word;
#line 253 "pwl.vala"
		_tmp18_ = g_utf8_normalize (_tmp17_, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 253 "pwl.vala"
		_tmp19_ = _tmp18_;
#line 253 "pwl.vala"
		_tmp20_ = g_hash_table_contains (_tmp16_, _tmp19_);
#line 253 "pwl.vala"
		_g_free0 (_tmp19_);
#line 253 "pwl.vala"
		if (_tmp20_) {
#line 254 "pwl.vala"
			result = 0;
#line 254 "pwl.vala"
			_g_free0 (lower_case_word);
#line 254 "pwl.vala"
			_g_free0 (word);
#line 254 "pwl.vala"
			return result;
#line 1724 "pwl.c"
		}
#line 256 "pwl.vala"
		if (all_caps) {
#line 1728 "pwl.c"
			gchar* title_case_word = NULL;
			const gchar* _tmp21_;
			gchar* _tmp22_;
			GHashTable* _tmp23_;
			const gchar* _tmp24_;
			gchar* _tmp25_;
			gchar* _tmp26_;
			gboolean _tmp27_;
#line 257 "pwl.vala"
			_tmp21_ = word;
#line 257 "pwl.vala"
			_tmp22_ = utf8_strtitle (_tmp21_);
#line 257 "pwl.vala"
			title_case_word = _tmp22_;
#line 258 "pwl.vala"
			_tmp23_ = self->priv->words;
#line 258 "pwl.vala"
			_tmp24_ = title_case_word;
#line 258 "pwl.vala"
			_tmp25_ = g_utf8_normalize (_tmp24_, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 258 "pwl.vala"
			_tmp26_ = _tmp25_;
#line 258 "pwl.vala"
			_tmp27_ = g_hash_table_contains (_tmp23_, _tmp26_);
#line 258 "pwl.vala"
			_g_free0 (_tmp26_);
#line 258 "pwl.vala"
			if (_tmp27_) {
#line 259 "pwl.vala"
				result = 0;
#line 259 "pwl.vala"
				_g_free0 (title_case_word);
#line 259 "pwl.vala"
				_g_free0 (lower_case_word);
#line 259 "pwl.vala"
				_g_free0 (word);
#line 259 "pwl.vala"
				return result;
#line 1767 "pwl.c"
			}
#line 256 "pwl.vala"
			_g_free0 (title_case_word);
#line 1771 "pwl.c"
		}
#line 251 "pwl.vala"
		_g_free0 (lower_case_word);
#line 1775 "pwl.c"
	}
#line 263 "pwl.vala"
	result = 1;
#line 263 "pwl.vala"
	_g_free0 (word);
#line 263 "pwl.vala"
	return result;
#line 1783 "pwl.c"
}

static gchar*
g_file_stream_read_line (FILE* self)
{
	gint c = 0;
	GString* ret = NULL;
	GString* _tmp3_;
	gchar* result;
#line 4101 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 4103 "glib-2.0.vapi"
	ret = NULL;
#line 4104 "glib-2.0.vapi"
	while (TRUE) {
#line 1799 "pwl.c"
		GString* _tmp0_;
		GString* _tmp2_;
#line 4104 "glib-2.0.vapi"
		c = fgetc (self);
#line 4104 "glib-2.0.vapi"
		if (!(c != EOF)) {
#line 4104 "glib-2.0.vapi"
			break;
#line 1808 "pwl.c"
		}
#line 4105 "glib-2.0.vapi"
		_tmp0_ = ret;
#line 4105 "glib-2.0.vapi"
		if (_tmp0_ == NULL) {
#line 1814 "pwl.c"
			GString* _tmp1_;
#line 4106 "glib-2.0.vapi"
			_tmp1_ = g_string_new ("");
#line 4106 "glib-2.0.vapi"
			_g_string_free0 (ret);
#line 4106 "glib-2.0.vapi"
			ret = _tmp1_;
#line 1822 "pwl.c"
		}
#line 4108 "glib-2.0.vapi"
		if (c == ((gint) '\n')) {
#line 4109 "glib-2.0.vapi"
			break;
#line 1828 "pwl.c"
		}
#line 4111 "glib-2.0.vapi"
		_tmp2_ = ret;
#line 4111 "glib-2.0.vapi"
		g_string_append_c ((GString*) _tmp2_, (gchar) c);
#line 1834 "pwl.c"
	}
#line 4113 "glib-2.0.vapi"
	_tmp3_ = ret;
#line 4113 "glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 4114 "glib-2.0.vapi"
		result = NULL;
#line 4114 "glib-2.0.vapi"
		_g_string_free0 (ret);
#line 4114 "glib-2.0.vapi"
		return result;
#line 1846 "pwl.c"
	} else {
		GString* _tmp4_;
		gchar* _tmp5_;
#line 4116 "glib-2.0.vapi"
		_tmp4_ = ret;
#line 4116 "glib-2.0.vapi"
		_tmp5_ = ((GString*) _tmp4_)->str;
#line 4116 "glib-2.0.vapi"
		((GString*) _tmp4_)->str = NULL;
#line 4116 "glib-2.0.vapi"
		result = _tmp5_;
#line 4116 "glib-2.0.vapi"
		_g_string_free0 (ret);
#line 4116 "glib-2.0.vapi"
		return result;
#line 1862 "pwl.c"
	}
}

static gchar*
string_chomp (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
#line 1399 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1400 "glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1400 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1401 "glib-2.0.vapi"
	g_strchomp (_result_);
#line 1402 "glib-2.0.vapi"
	result = _result_;
#line 1402 "glib-2.0.vapi"
	return result;
#line 1884 "pwl.c"
}

static void
enchant_pwl_refresh_from_file (EnchantPWL* self,
                               EnchantDict* session)
{
	const gchar* _tmp0_;
	struct stat stats = {0};
	const gchar* _tmp1_;
	struct stat _tmp2_ = {0};
	gint _tmp3_;
	struct stat _tmp4_;
	FILE* f = NULL;
	const gchar* _tmp5_;
	FILE* _tmp6_;
	FILE* _tmp7_;
	GHashFunc _tmp15_;
	GEqualFunc _tmp16_;
	GHashTable* _tmp17_;
	struct stat _tmp18_;
	FILE* _tmp19_;
	gsize line_number = 0UL;
	gchar* line = NULL;
	FILE* _tmp38_;
#line 266 "pwl.vala"
	g_return_if_fail (self != NULL);
#line 266 "pwl.vala"
	g_return_if_fail (session != NULL);
#line 267 "pwl.vala"
	_tmp0_ = self->priv->filename;
#line 267 "pwl.vala"
	if (_tmp0_ == NULL) {
#line 268 "pwl.vala"
		return;
#line 1919 "pwl.c"
	}
#line 271 "pwl.vala"
	_tmp1_ = self->priv->filename;
#line 271 "pwl.vala"
	_tmp3_ = stat (_tmp1_, &_tmp2_);
#line 271 "pwl.vala"
	stats = _tmp2_;
#line 271 "pwl.vala"
	if (_tmp3_ == -1) {
#line 272 "pwl.vala"
		return;
#line 1931 "pwl.c"
	}
#line 273 "pwl.vala"
	_tmp4_ = stats;
#line 273 "pwl.vala"
	if (self->priv->file_changed == _tmp4_.st_mtime) {
#line 274 "pwl.vala"
		return;
#line 1939 "pwl.c"
	}
#line 276 "pwl.vala"
	_tmp5_ = self->priv->filename;
#line 276 "pwl.vala"
	_tmp6_ = g_fopen (_tmp5_, "r");
#line 276 "pwl.vala"
	f = _tmp6_;
#line 277 "pwl.vala"
	_tmp7_ = f;
#line 277 "pwl.vala"
	if (_tmp7_ == NULL) {
#line 278 "pwl.vala"
		_fclose0 (f);
#line 278 "pwl.vala"
		return;
#line 1955 "pwl.c"
	}
#line 281 "pwl.vala"
	if (!self->priv->exclude) {
#line 1959 "pwl.c"
		GHashTable* _tmp8_;
		GList* _tmp9_;
#line 282 "pwl.vala"
		_tmp8_ = self->priv->words;
#line 282 "pwl.vala"
		_tmp9_ = g_hash_table_get_keys (_tmp8_);
#line 1966 "pwl.c"
		{
			GList* w_collection = NULL;
			GList* w_it = NULL;
#line 282 "pwl.vala"
			w_collection = _tmp9_;
#line 282 "pwl.vala"
			for (w_it = w_collection; w_it != NULL; w_it = w_it->next) {
#line 1974 "pwl.c"
				gchar* _tmp10_;
				gchar* w = NULL;
#line 282 "pwl.vala"
				_tmp10_ = g_strdup ((const gchar*) w_it->data);
#line 282 "pwl.vala"
				w = _tmp10_;
#line 1981 "pwl.c"
				{
					const gchar* _tmp11_;
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
#line 283 "pwl.vala"
					_tmp11_ = w;
#line 283 "pwl.vala"
					_tmp12_ = w;
#line 283 "pwl.vala"
					_tmp13_ = strlen (_tmp12_);
#line 283 "pwl.vala"
					_tmp14_ = _tmp13_;
#line 283 "pwl.vala"
					enchant_dict_remove_from_session (session, _tmp11_, (ssize_t) _tmp14_);
#line 282 "pwl.vala"
					_g_free0 (w);
#line 1999 "pwl.c"
				}
			}
#line 282 "pwl.vala"
			(w_collection == NULL) ? NULL : (w_collection = (g_list_free (w_collection), NULL));
#line 2004 "pwl.c"
		}
	}
#line 286 "pwl.vala"
	_tmp15_ = g_str_hash;
#line 286 "pwl.vala"
	_tmp16_ = g_str_equal;
#line 286 "pwl.vala"
	_tmp17_ = g_hash_table_new_full (_tmp15_, _tmp16_, _g_free0_, _g_free0_);
#line 286 "pwl.vala"
	_g_hash_table_unref0 (self->priv->words);
#line 286 "pwl.vala"
	self->priv->words = _tmp17_;
#line 288 "pwl.vala"
	_tmp18_ = stats;
#line 288 "pwl.vala"
	self->priv->file_changed = _tmp18_.st_mtime;
#line 289 "pwl.vala"
	_tmp19_ = f;
#line 289 "pwl.vala"
	lock_file (_tmp19_);
#line 291 "pwl.vala"
	line_number = (gsize) 1;
#line 2027 "pwl.c"
	{
		gboolean _tmp20_ = FALSE;
#line 293 "pwl.vala"
		_tmp20_ = TRUE;
#line 293 "pwl.vala"
		while (TRUE) {
#line 2034 "pwl.c"
			FILE* _tmp22_;
			gchar* _tmp23_;
			const gchar* _tmp24_;
			gboolean _tmp25_ = FALSE;
			const gchar* _tmp30_;
			gchar* _tmp31_;
			gboolean _tmp32_ = FALSE;
			const gchar* _tmp33_;
#line 293 "pwl.vala"
			if (!_tmp20_) {
#line 2045 "pwl.c"
				gsize _tmp21_;
#line 293 "pwl.vala"
				line_number = line_number + 1;
#line 293 "pwl.vala"
				_tmp21_ = line_number;
#line 2051 "pwl.c"
			}
#line 293 "pwl.vala"
			_tmp20_ = FALSE;
#line 293 "pwl.vala"
			_tmp22_ = f;
#line 293 "pwl.vala"
			_tmp23_ = g_file_stream_read_line (_tmp22_);
#line 293 "pwl.vala"
			_g_free0 (line);
#line 293 "pwl.vala"
			line = _tmp23_;
#line 293 "pwl.vala"
			_tmp24_ = line;
#line 293 "pwl.vala"
			if (!(_tmp24_ != NULL)) {
#line 293 "pwl.vala"
				break;
#line 2069 "pwl.c"
			}
#line 294 "pwl.vala"
			if (line_number == ((gsize) 1)) {
#line 2073 "pwl.c"
				const gchar* _tmp26_;
#line 294 "pwl.vala"
				_tmp26_ = line;
#line 294 "pwl.vala"
				_tmp25_ = BOM == string_get_char (_tmp26_, (glong) 0);
#line 2079 "pwl.c"
			} else {
#line 294 "pwl.vala"
				_tmp25_ = FALSE;
#line 2083 "pwl.c"
			}
#line 294 "pwl.vala"
			if (_tmp25_) {
#line 2087 "pwl.c"
				const gchar* _tmp27_;
				const gchar* _tmp28_;
				gchar* _tmp29_;
#line 295 "pwl.vala"
				_tmp27_ = line;
#line 295 "pwl.vala"
				_tmp28_ = g_utf8_next_char (_tmp27_);
#line 295 "pwl.vala"
				_tmp29_ = g_strdup (_tmp28_);
#line 295 "pwl.vala"
				_g_free0 (line);
#line 295 "pwl.vala"
				line = _tmp29_;
#line 2101 "pwl.c"
			}
#line 297 "pwl.vala"
			_tmp30_ = line;
#line 297 "pwl.vala"
			_tmp31_ = string_chomp (_tmp30_);
#line 297 "pwl.vala"
			_g_free0 (line);
#line 297 "pwl.vala"
			line = _tmp31_;
#line 298 "pwl.vala"
			_tmp33_ = line;
#line 298 "pwl.vala"
			if (string_get (_tmp33_, (glong) 0) != '\0') {
#line 2115 "pwl.c"
				const gchar* _tmp34_;
#line 298 "pwl.vala"
				_tmp34_ = line;
#line 298 "pwl.vala"
				_tmp32_ = string_get (_tmp34_, (glong) 0) != '#';
#line 2121 "pwl.c"
			} else {
#line 298 "pwl.vala"
				_tmp32_ = FALSE;
#line 2125 "pwl.c"
			}
#line 298 "pwl.vala"
			if (_tmp32_) {
#line 2129 "pwl.c"
				const gchar* _tmp35_;
#line 299 "pwl.vala"
				_tmp35_ = line;
#line 299 "pwl.vala"
				if (g_utf8_validate (_tmp35_, (gssize) -1, NULL)) {
#line 2135 "pwl.c"
					const gchar* _tmp36_;
#line 300 "pwl.vala"
					_tmp36_ = line;
#line 300 "pwl.vala"
					enchant_pwl_add_to_table (self, _tmp36_);
#line 2141 "pwl.c"
				} else {
					const gchar* _tmp37_;
#line 302 "pwl.vala"
					_tmp37_ = self->priv->filename;
#line 302 "pwl.vala"
					g_warning ("pwl.vala:302: Bad UTF-8 sequence in %s at line:%zu", _tmp37_, line_number);
#line 2148 "pwl.c"
				}
			}
		}
	}
#line 306 "pwl.vala"
	_tmp38_ = f;
#line 306 "pwl.vala"
	unlock_file (_tmp38_);
#line 309 "pwl.vala"
	if (!self->priv->exclude) {
#line 2159 "pwl.c"
		GHashTable* _tmp39_;
		GList* _tmp40_;
#line 310 "pwl.vala"
		_tmp39_ = self->priv->words;
#line 310 "pwl.vala"
		_tmp40_ = g_hash_table_get_keys (_tmp39_);
#line 2166 "pwl.c"
		{
			GList* w_collection = NULL;
			GList* w_it = NULL;
#line 310 "pwl.vala"
			w_collection = _tmp40_;
#line 310 "pwl.vala"
			for (w_it = w_collection; w_it != NULL; w_it = w_it->next) {
#line 2174 "pwl.c"
				gchar* _tmp41_;
				gchar* w = NULL;
#line 310 "pwl.vala"
				_tmp41_ = g_strdup ((const gchar*) w_it->data);
#line 310 "pwl.vala"
				w = _tmp41_;
#line 2181 "pwl.c"
				{
					const gchar* _tmp42_;
					const gchar* _tmp43_;
					gint _tmp44_;
					gint _tmp45_;
#line 311 "pwl.vala"
					_tmp42_ = w;
#line 311 "pwl.vala"
					_tmp43_ = w;
#line 311 "pwl.vala"
					_tmp44_ = strlen (_tmp43_);
#line 311 "pwl.vala"
					_tmp45_ = _tmp44_;
#line 311 "pwl.vala"
					enchant_dict_add_to_session (session, _tmp42_, (ssize_t) _tmp45_);
#line 310 "pwl.vala"
					_g_free0 (w);
#line 2199 "pwl.c"
				}
			}
#line 310 "pwl.vala"
			(w_collection == NULL) ? NULL : (w_collection = (g_list_free (w_collection), NULL));
#line 2204 "pwl.c"
		}
	}
#line 266 "pwl.vala"
	_g_free0 (line);
#line 266 "pwl.vala"
	_fclose0 (f);
#line 2211 "pwl.c"
}

static void
value_enchant_pwl_init (GValue* value)
{
#line 124 "pwl.vala"
	value->data[0].v_pointer = NULL;
#line 2219 "pwl.c"
}

static void
value_enchant_pwl_free_value (GValue* value)
{
#line 124 "pwl.vala"
	if (value->data[0].v_pointer) {
#line 124 "pwl.vala"
		enchant_pwl_unref (value->data[0].v_pointer);
#line 2229 "pwl.c"
	}
}

static void
value_enchant_pwl_copy_value (const GValue* src_value,
                              GValue* dest_value)
{
#line 124 "pwl.vala"
	if (src_value->data[0].v_pointer) {
#line 124 "pwl.vala"
		dest_value->data[0].v_pointer = enchant_pwl_ref (src_value->data[0].v_pointer);
#line 2241 "pwl.c"
	} else {
#line 124 "pwl.vala"
		dest_value->data[0].v_pointer = NULL;
#line 2245 "pwl.c"
	}
}

static gpointer
value_enchant_pwl_peek_pointer (const GValue* value)
{
#line 124 "pwl.vala"
	return value->data[0].v_pointer;
#line 2254 "pwl.c"
}

static gchar*
value_enchant_pwl_collect_value (GValue* value,
                                 guint n_collect_values,
                                 GTypeCValue* collect_values,
                                 guint collect_flags)
{
#line 124 "pwl.vala"
	if (collect_values[0].v_pointer) {
#line 2265 "pwl.c"
		EnchantPWL * object;
		object = collect_values[0].v_pointer;
#line 124 "pwl.vala"
		if (object->parent_instance.g_class == NULL) {
#line 124 "pwl.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 2272 "pwl.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 124 "pwl.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 2276 "pwl.c"
		}
#line 124 "pwl.vala"
		value->data[0].v_pointer = enchant_pwl_ref (object);
#line 2280 "pwl.c"
	} else {
#line 124 "pwl.vala"
		value->data[0].v_pointer = NULL;
#line 2284 "pwl.c"
	}
#line 124 "pwl.vala"
	return NULL;
#line 2288 "pwl.c"
}

static gchar*
value_enchant_pwl_lcopy_value (const GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	EnchantPWL ** object_p;
	object_p = collect_values[0].v_pointer;
#line 124 "pwl.vala"
	if (!object_p) {
#line 124 "pwl.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 2303 "pwl.c"
	}
#line 124 "pwl.vala"
	if (!value->data[0].v_pointer) {
#line 124 "pwl.vala"
		*object_p = NULL;
#line 2309 "pwl.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 124 "pwl.vala"
		*object_p = value->data[0].v_pointer;
#line 2313 "pwl.c"
	} else {
#line 124 "pwl.vala"
		*object_p = enchant_pwl_ref (value->data[0].v_pointer);
#line 2317 "pwl.c"
	}
#line 124 "pwl.vala"
	return NULL;
#line 2321 "pwl.c"
}

GParamSpec*
param_spec_enchant_pwl (const gchar* name,
                        const gchar* nick,
                        const gchar* blurb,
                        GType object_type,
                        GParamFlags flags)
{
	ParamSpecEnchantPWL* spec;
#line 124 "pwl.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_ENCHANT_PWL), NULL);
#line 124 "pwl.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 124 "pwl.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 124 "pwl.vala"
	return G_PARAM_SPEC (spec);
#line 2340 "pwl.c"
}

gpointer
value_get_enchant_pwl (const GValue* value)
{
#line 124 "pwl.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ENCHANT_PWL), NULL);
#line 124 "pwl.vala"
	return value->data[0].v_pointer;
#line 2350 "pwl.c"
}

void
value_set_enchant_pwl (GValue* value,
                       gpointer v_object)
{
	EnchantPWL * old;
#line 124 "pwl.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ENCHANT_PWL));
#line 124 "pwl.vala"
	old = value->data[0].v_pointer;
#line 124 "pwl.vala"
	if (v_object) {
#line 124 "pwl.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ENCHANT_PWL));
#line 124 "pwl.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 124 "pwl.vala"
		value->data[0].v_pointer = v_object;
#line 124 "pwl.vala"
		enchant_pwl_ref (value->data[0].v_pointer);
#line 2372 "pwl.c"
	} else {
#line 124 "pwl.vala"
		value->data[0].v_pointer = NULL;
#line 2376 "pwl.c"
	}
#line 124 "pwl.vala"
	if (old) {
#line 124 "pwl.vala"
		enchant_pwl_unref (old);
#line 2382 "pwl.c"
	}
}

void
value_take_enchant_pwl (GValue* value,
                        gpointer v_object)
{
	EnchantPWL * old;
#line 124 "pwl.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ENCHANT_PWL));
#line 124 "pwl.vala"
	old = value->data[0].v_pointer;
#line 124 "pwl.vala"
	if (v_object) {
#line 124 "pwl.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ENCHANT_PWL));
#line 124 "pwl.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 124 "pwl.vala"
		value->data[0].v_pointer = v_object;
#line 2403 "pwl.c"
	} else {
#line 124 "pwl.vala"
		value->data[0].v_pointer = NULL;
#line 2407 "pwl.c"
	}
#line 124 "pwl.vala"
	if (old) {
#line 124 "pwl.vala"
		enchant_pwl_unref (old);
#line 2413 "pwl.c"
	}
}

static void
enchant_pwl_class_init (EnchantPWLClass * klass,
                        gpointer klass_data)
{
#line 124 "pwl.vala"
	enchant_pwl_parent_class = g_type_class_peek_parent (klass);
#line 124 "pwl.vala"
	((EnchantPWLClass *) klass)->finalize = enchant_pwl_finalize;
#line 124 "pwl.vala"
	g_type_class_adjust_private_offset (klass, &EnchantPWL_private_offset);
#line 2427 "pwl.c"
}

static void
enchant_pwl_instance_init (EnchantPWL * self,
                           gpointer klass)
{
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
#line 124 "pwl.vala"
	self->priv = enchant_pwl_get_instance_private (self);
#line 126 "pwl.vala"
	self->priv->exclude = FALSE;
#line 127 "pwl.vala"
	self->priv->file_changed = (time_t) 0;
#line 128 "pwl.vala"
	_tmp0_ = g_str_hash;
#line 128 "pwl.vala"
	_tmp1_ = g_str_equal;
#line 128 "pwl.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, _g_free0_);
#line 128 "pwl.vala"
	self->priv->words = _tmp2_;
#line 124 "pwl.vala"
	self->ref_count = 1;
#line 2453 "pwl.c"
}

static void
enchant_pwl_finalize (EnchantPWL * obj)
{
	EnchantPWL * self;
#line 124 "pwl.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ENCHANT_PWL, EnchantPWL);
#line 124 "pwl.vala"
	g_signal_handlers_destroy (self);
#line 125 "pwl.vala"
	_g_free0 (self->priv->filename);
#line 128 "pwl.vala"
	_g_hash_table_unref0 (self->priv->words);
#line 2468 "pwl.c"
}

static GType
enchant_pwl_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_enchant_pwl_init, value_enchant_pwl_free_value, value_enchant_pwl_copy_value, value_enchant_pwl_peek_pointer, "p", value_enchant_pwl_collect_value, "p", value_enchant_pwl_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (EnchantPWLClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enchant_pwl_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnchantPWL), 0, (GInstanceInitFunc) enchant_pwl_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType enchant_pwl_type_id;
	enchant_pwl_type_id = g_type_register_fundamental (g_type_fundamental_next (), "EnchantPWL", &g_define_type_info, &g_define_type_fundamental_info, 0);
	EnchantPWL_private_offset = g_type_add_instance_private (enchant_pwl_type_id, sizeof (EnchantPWLPrivate));
	return enchant_pwl_type_id;
}

GType
enchant_pwl_get_type (void)
{
	static volatile gsize enchant_pwl_type_id__once = 0;
	if (g_once_init_enter (&enchant_pwl_type_id__once)) {
		GType enchant_pwl_type_id;
		enchant_pwl_type_id = enchant_pwl_get_type_once ();
		g_once_init_leave (&enchant_pwl_type_id__once, enchant_pwl_type_id);
	}
	return enchant_pwl_type_id__once;
}

gpointer
enchant_pwl_ref (gpointer instance)
{
	EnchantPWL * self;
	self = instance;
#line 124 "pwl.vala"
	g_atomic_int_inc (&self->ref_count);
#line 124 "pwl.vala"
	return instance;
#line 2504 "pwl.c"
}

void
enchant_pwl_unref (gpointer instance)
{
	EnchantPWL * self;
	self = instance;
#line 124 "pwl.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 124 "pwl.vala"
		ENCHANT_PWL_GET_CLASS (self)->finalize (self);
#line 124 "pwl.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 2518 "pwl.c"
	}
}

gint
check_impl (EnchantProviderDict* me,
            const gchar* word,
            size_t len)
{
	gint result;
#line 316 "pwl.vala"
	g_return_val_if_fail (me != NULL, -1);
#line 316 "pwl.vala"
	g_return_val_if_fail (word != NULL, -1);
#line 317 "pwl.vala"
	result = 1;
#line 317 "pwl.vala"
	return result;
#line 2536 "pwl.c"
}

gchar**
suggest_impl (EnchantProviderDict* me,
              const gchar* word,
              size_t len,
              size_t* result_length1)
{
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** result;
#line 321 "pwl.vala"
	g_return_val_if_fail (me != NULL, NULL);
#line 321 "pwl.vala"
	g_return_val_if_fail (word != NULL, NULL);
#line 322 "pwl.vala"
	_tmp0_ = NULL;
#line 322 "pwl.vala"
	_tmp0__length1 = 0;
#line 322 "pwl.vala"
	if (result_length1) {
#line 322 "pwl.vala"
		*result_length1 = _tmp0__length1;
#line 2560 "pwl.c"
	}
#line 322 "pwl.vala"
	result = _tmp0_;
#line 322 "pwl.vala"
	return result;
#line 2566 "pwl.c"
}

static gint
_check_impl_dict_check (EnchantProviderDict* me,
                        const gchar* word,
                        size_t len)
{
	gint result;
	result = check_impl (me, word, len);
#line 328 "pwl.vala"
	return result;
#line 2578 "pwl.c"
}

static gchar**
_suggest_impl_dict_suggest (EnchantProviderDict* me,
                            const gchar* word,
                            size_t len,
                            size_t* result_length1)
{
	gchar** result;
	result = suggest_impl (me, word, len, result_length1);
#line 329 "pwl.vala"
	return result;
#line 2591 "pwl.c"
}

EnchantPwlDict*
enchant_pwl_dict_construct (GType object_type)
{
	EnchantPwlDict* self = NULL;
#line 327 "pwl.vala"
	self = (EnchantPwlDict*) enchant_provider_dict_construct (object_type, NULL, "Personal Wordlist");
#line 328 "pwl.vala"
	((EnchantProviderDict*) self)->check_method = _check_impl_dict_check;
#line 329 "pwl.vala"
	((EnchantProviderDict*) self)->suggest_method = _suggest_impl_dict_suggest;
#line 326 "pwl.vala"
	return self;
#line 2606 "pwl.c"
}

EnchantPwlDict*
enchant_pwl_dict_new (void)
{
#line 326 "pwl.vala"
	return enchant_pwl_dict_construct (TYPE_ENCHANT_PWL_DICT);
#line 2614 "pwl.c"
}

static void
enchant_pwl_dict_class_init (EnchantPwlDictClass * klass,
                             gpointer klass_data)
{
#line 325 "pwl.vala"
	enchant_pwl_dict_parent_class = g_type_class_peek_parent (klass);
#line 2623 "pwl.c"
}

static void
enchant_pwl_dict_instance_init (EnchantPwlDict * self,
                                gpointer klass)
{
}

static GType
enchant_pwl_dict_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EnchantPwlDictClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enchant_pwl_dict_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnchantPwlDict), 0, (GInstanceInitFunc) enchant_pwl_dict_instance_init, NULL };
	GType enchant_pwl_dict_type_id;
	enchant_pwl_dict_type_id = g_type_register_static (TYPE_ENCHANT_PROVIDER_DICT, "EnchantPwlDict", &g_define_type_info, 0);
	return enchant_pwl_dict_type_id;
}

GType
enchant_pwl_dict_get_type (void)
{
	static volatile gsize enchant_pwl_dict_type_id__once = 0;
	if (g_once_init_enter (&enchant_pwl_dict_type_id__once)) {
		GType enchant_pwl_dict_type_id;
		enchant_pwl_dict_type_id = enchant_pwl_dict_get_type_once ();
		g_once_init_leave (&enchant_pwl_dict_type_id__once, enchant_pwl_dict_type_id);
	}
	return enchant_pwl_dict_type_id__once;
}
