#define PKGDATADIR "/usr/local/share/enchant"
#define PKGLIBDIR "/usr/local/lib/enchant"
#define SYSCONFDIR "/usr/local/etc"
#define INSTALLPREFIX "/usr/local"
#define ENCHANT_MAJOR_VERSION "2"
#define ENCHANT_VERSION_STRING "2.8.15"
